#!/bin/bash

# Validate that required env vars are set
: "${MIKU_KEY_ALIAS:?Need to set MIKU_KEY_ALIAS}"
: "${MIKU_KEY_PASSWORD:?Need to set MIKU_KEY_PASSWORD}"

keytool -genkeypair -v \
 -keystore release.keystore \
 -alias mikuone \
 -keyalg RSA \
 -keysize 2048 \
 -validity 10000 \
 -storepass "M!ku0n3Ummah" \
 -keypass "M!ku0n3Ummah" \
 -dname "CN=Miku One, OU=MikuOne, O=MikuOne, L=Jakarta, S=Jakarta, C=Indonesia"

