package tech.kayys.accounting.model;

public enum AccountCategory {
    CURRENT_ASSET, FIXED_ASSET, CURRENT_LIABILITY, LONG_TERM_LIABILITY,
    PAID_IN_CAPITAL, RETAINED_EARNINGS, OPERATING_REVENUE, NON_OPERATING_REVENUE,
    OPERATING_EXPENSE, NON_OPERATING_EXPENSE, ADMINISTRATIVE_EXPENSE, SELLING_EXPENSE
}