import 'package:flutter/material.dart';

import 'widget_gallery_item.dart';

final widgetGalleryItems = List<WidgetGalleryItem>.unmodifiable([
  WidgetGalleryItem(
    id: 'heading1',
    name: 'Heading 1',
    description: 'Large section heading',
    icon: Icons.title,
    category: 'basic',
    color: Colors.blue,
  ),
  WidgetGalleryItem(
    id: 'heading2',
    name: 'Heading 2',
    description: 'Medium section heading',
    icon: Icons.title,
    category: 'basic',
    color: Colors.blue.shade400,
  ),
  WidgetGalleryItem(
    id: 'heading3',
    name: 'Heading 3',
    description: 'Small section heading',
    icon: Icons.title,
    category: 'basic',
    color: Colors.blue.shade300,
  ),
  WidgetGalleryItem(
    id: 'paragraph',
    name: 'Paragraph',
    description: 'Plain text block',
    icon: Icons.text_fields,
    category: 'basic',
    color: Colors.grey,
  ),
  WidgetGalleryItem(
    id: 'bullet',
    name: 'Bullet List',
    description: 'Simple bulleted list',
    icon: Icons.format_list_bulleted,
    category: 'basic',
    color: Colors.grey.shade700,
  ),
  WidgetGalleryItem(
    id: 'numbered',
    name: 'Numbered List',
    description: 'Numbered list',
    icon: Icons.format_list_numbered,
    category: 'basic',
    color: Colors.grey.shade700,
  ),
  WidgetGalleryItem(
    id: 'checkbox',
    name: 'Checklist',
    description: 'To-do list with checkboxes',
    icon: Icons.check_box,
    category: 'basic',
    color: Colors.green,
  ),
  WidgetGalleryItem(
    id: 'quote',
    name: 'Quote',
    description: 'Highlight a quote',
    icon: Icons.format_quote,
    category: 'basic',
    color: Colors.purple,
  ),
  WidgetGalleryItem(
    id: 'code',
    name: 'Code Block',
    description: 'Code with syntax highlighting',
    icon: Icons.code,
    category: 'basic',
    color: Colors.orange,
  ),
  WidgetGalleryItem(
    id: 'divider',
    name: 'Divider',
    description: 'Visual separator',
    icon: Icons.horizontal_rule,
    category: 'basic',
    color: Colors.grey,
  ),
  WidgetGalleryItem(
    id: 'callout',
    name: 'Callout',
    description: 'Highlighted information',
    icon: Icons.campaign,
    category: 'basic',
    color: Colors.amber,
  ),
  WidgetGalleryItem(
    id: 'table',
    name: 'Table',
    description: 'Insert a table',
    icon: Icons.table_chart,
    category: 'basic',
    color: Colors.teal,
  ),
  WidgetGalleryItem(
    id: 'image',
    name: 'Image',
    description: 'Upload or embed image',
    icon: Icons.image,
    category: 'media',
    color: Colors.pink,
  ),
  WidgetGalleryItem(
    id: 'video',
    name: 'Video',
    description: 'Embed video file',
    icon: Icons.videocam,
    category: 'media',
    color: Colors.red,
  ),
  WidgetGalleryItem(
    id: 'audio',
    name: 'Audio',
    description: 'Embed audio file',
    icon: Icons.audiotrack,
    category: 'media',
    color: Colors.deepPurple,
  ),
  WidgetGalleryItem(
    id: 'file',
    name: 'File',
    description: 'Attach any file',
    icon: Icons.attach_file,
    category: 'media',
    color: Colors.blueGrey,
  ),
  WidgetGalleryItem(
    id: 'youtube',
    name: 'YouTube',
    description: 'Embed YouTube video',
    icon: Icons.play_circle_filled,
    category: 'embed',
    color: Colors.red,
  ),
  WidgetGalleryItem(
    id: 'twitter',
    name: 'Twitter/X',
    description: 'Embed tweet',
    icon: Icons.chat_bubble,
    category: 'embed',
    color: Colors.lightBlue,
  ),
  WidgetGalleryItem(
    id: 'maps',
    name: 'Google Maps',
    description: 'Embed location map',
    icon: Icons.map,
    category: 'embed',
    color: Colors.green,
  ),
  WidgetGalleryItem(
    id: 'iframe',
    name: 'Web Embed',
    description: 'Embed any website',
    icon: Icons.web,
    category: 'embed',
    color: Colors.indigo,
  ),
  WidgetGalleryItem(
    id: 'figma',
    name: 'Figma',
    description: 'Embed Figma design',
    icon: Icons.design_services,
    category: 'embed',
    color: Colors.purple,
  ),
  WidgetGalleryItem(
    id: 'chart_bar',
    name: 'Bar Chart',
    description: 'Vertical bar chart',
    icon: Icons.bar_chart,
    category: 'chart',
    color: Colors.blue,
  ),
  WidgetGalleryItem(
    id: 'chart_line',
    name: 'Line Chart',
    description: 'Line graph',
    icon: Icons.show_chart,
    category: 'chart',
    color: Colors.green,
  ),
  WidgetGalleryItem(
    id: 'chart_pie',
    name: 'Pie Chart',
    description: 'Circular pie chart',
    icon: Icons.pie_chart,
    category: 'chart',
    color: Colors.orange,
  ),
  WidgetGalleryItem(
    id: 'chart_area',
    name: 'Area Chart',
    description: 'Filled area graph',
    icon: Icons.area_chart,
    category: 'chart',
    color: Colors.purple,
  ),
  WidgetGalleryItem(
    id: 'math',
    name: 'Math Equation',
    description: 'LaTeX math formula',
    icon: Icons.functions,
    category: 'advanced',
    color: Colors.deepOrange,
  ),
  WidgetGalleryItem(
    id: 'mermaid',
    name: 'Diagram',
    description: 'Flowchart/diagram',
    icon: Icons.account_tree,
    category: 'advanced',
    color: Colors.cyan,
  ),
  WidgetGalleryItem(
    id: 'calendar',
    name: 'Calendar',
    description: 'Date picker/calendar',
    icon: Icons.calendar_month,
    category: 'advanced',
    color: Colors.red.shade400,
  ),
  WidgetGalleryItem(
    id: 'kanban',
    name: 'Kanban Board',
    description: 'Task board',
    icon: Icons.view_column,
    category: 'advanced',
    color: Colors.deepPurple,
  ),
  WidgetGalleryItem(
    id: 'button',
    name: 'Button',
    description: 'Interactive button',
    icon: Icons.smart_button,
    category: 'advanced',
    color: Colors.blue.shade600,
  ),
]);
