/// Identifies the operating workflow that produced an activity event.
enum RestaurantOperationActivityKind {
  taskCompleted,
  stationStatusChanged,
  zoneStatusChanged,
  reservationStatusChanged,
  menuRiskResolved,
  menuCatalogReviewed,
  recipeProductionReviewed;

  String get label => switch (this) {
    RestaurantOperationActivityKind.taskCompleted => 'Task completed',
    RestaurantOperationActivityKind.stationStatusChanged => 'Station updated',
    RestaurantOperationActivityKind.zoneStatusChanged => 'Floor updated',
    RestaurantOperationActivityKind.reservationStatusChanged =>
      'Reservation updated',
    RestaurantOperationActivityKind.menuRiskResolved => 'Menu restocked',
    RestaurantOperationActivityKind.menuCatalogReviewed => 'Catalog reviewed',
    RestaurantOperationActivityKind.recipeProductionReviewed =>
      'Recipe reviewed',
  };
}

/// Records one operational event generated by a restaurant workflow action.
class RestaurantOperationActivity {
  const RestaurantOperationActivity({
    required this.id,
    required this.kind,
    required this.title,
    required this.description,
    required this.createdAt,
    this.actorLabel = 'Shift lead',
  });

  final String id;
  final RestaurantOperationActivityKind kind;
  final String title;
  final String description;
  final DateTime createdAt;
  final String actorLabel;
}
