// lib/core/models/gallery_models.dart — complete DTO set for all 17 modules.

class GFolder { final int id; final String path,displayName; final int? lastIndexedAt; final int itemCount; const GFolder({required this.id,required this.path,required this.displayName,this.lastIndexedAt,required this.itemCount}); }
class GMediaItem { final int id,folderId,fileSize,modifiedAt,rating,flag,indexedAt; final String filePath,fileName,mimeType; final int? width,height,createdAt; final String? contentHash,thumbnailPath; final String colorLabel; final bool isRaw; const GMediaItem({required this.id,required this.folderId,required this.filePath,required this.fileName,required this.fileSize,this.width,this.height,required this.mimeType,this.createdAt,required this.modifiedAt,this.contentHash,required this.rating,required this.flag,this.colorLabel='',required this.isRaw,this.thumbnailPath,required this.indexedAt}); String get aspectRatio=>(width!=null&&height!=null)?'${width}×$height':''; String get fileSizeFormatted=>fileSize<1048576?'${(fileSize/1024).toStringAsFixed(1)}KB':'${(fileSize/1048576).toStringAsFixed(1)}MB'; }
class GExifData { final int itemId; final String? cameraMake,cameraModel,lens,shutterSpeed,colorSpace,exposureMode,whiteBalance; final int? iso; final double? aperture,focalLength,latitude,longitude; final bool? flash; final String rawJson; const GExifData({required this.itemId,this.cameraMake,this.cameraModel,this.lens,this.iso,this.shutterSpeed,this.aperture,this.focalLength,this.flash,this.latitude,this.longitude,this.colorSpace,this.exposureMode,this.whiteBalance,this.rawJson='{}'}); String? get apertureFormatted=>aperture!=null?'f/${aperture!.toStringAsFixed(1)}':null; bool get hasGps=>latitude!=null&&longitude!=null; }
class GGalleryStats { final int totalItems,totalFolders,totalSizeBytes,rawCount,flaggedCount,rejectedCount; const GGalleryStats({required this.totalItems,required this.totalFolders,required this.totalSizeBytes,required this.rawCount,required this.flaggedCount,required this.rejectedCount}); String get totalSizeFormatted{final gb=totalSizeBytes/(1024*1024*1024);return gb>=1?'${gb.toStringAsFixed(2)} GB':'${(totalSizeBytes/1048576).toStringAsFixed(1)} MB';} }
class GIndexEvent { final String kind; final String? folder,currentFile,thumbPath,message; final int? indexed,total,itemId,durationMs; const GIndexEvent({required this.kind,this.folder,this.indexed,this.total,this.currentFile,this.itemId,this.thumbPath,this.durationMs,this.message}); }
class GWatchEvent { final String kind,path; const GWatchEvent({required this.kind,required this.path}); }
class GExportEvent { final String kind; final int? done,total,durationMs; final String? outputPath,message; const GExportEvent({required this.kind,this.done,this.total,this.outputPath,this.message,this.durationMs}); }
class GDuplicateCluster { final int representativeId; final List<int> itemIds; final int maxDistance; const GDuplicateCluster({required this.representativeId,required this.itemIds,required this.maxDistance}); }
class GHistogram { final List<double> r,g,b,luma; const GHistogram({required this.r,required this.g,required this.b,required this.luma}); }
class GRenamePreview { final int itemId; final String oldName,newName,newPath,action; final bool conflict; const GRenamePreview({required this.itemId,required this.oldName,required this.newName,required this.newPath,required this.conflict,required this.action}); }
class GRenameResult { final int itemId; final String oldPath,newPath; final bool success; final String? error; const GRenameResult({required this.itemId,required this.oldPath,required this.newPath,required this.success,this.error}); }
class GXmpData { final int rating,flag; final String label; final String? title,description; final List<String> keywords; const GXmpData({required this.rating,required this.flag,required this.label,this.title,this.description,this.keywords=const[]}); }
class GSlideshowConfig { final String title,json; final int slideCount,totalDurationMs; const GSlideshowConfig({required this.title,required this.slideCount,required this.totalDurationMs,required this.json}); String get durationFormatted{final s=totalDurationMs~/1000;return '${s~/60}:${(s%60).toString().padLeft(2,'0')}';} }
class GMapCluster { final double lat,lng; final List<int> itemIds; final String? thumbPath; final List<double> bbox; const GMapCluster({required this.lat,required this.lng,required this.itemIds,this.thumbPath,required this.bbox}); int get count=>itemIds.length; }
class GCollection { final int id,itemCount,createdAt; final String name,description,kind; final int? coverItemId; const GCollection({required this.id,required this.name,required this.description,required this.itemCount,required this.createdAt,required this.kind,this.coverItemId}); bool get isSmart=>kind=='smart'; }
class GExportPreset { final String name,id,description; const GExportPreset({required this.name,required this.id,required this.description}); }
class GAnalyticsSummary { final int totalItems,totalSizeBytes,flagged,rejected,rated,rawCount,geotagged; const GAnalyticsSummary({required this.totalItems,required this.totalSizeBytes,required this.flagged,required this.rejected,required this.rated,required this.rawCount,required this.geotagged}); String get sizeFormatted{final gb=totalSizeBytes/(1024*1024*1024);return gb>=1?'${gb.toStringAsFixed(2)} GB':'${(totalSizeBytes/1048576).toStringAsFixed(1)} MB';} }
class GPrintLayout { final String name,id; final int rows,cols; const GPrintLayout({required this.name,required this.id,required this.rows,required this.cols}); }
class GSavedSearch { final int id; final String name,queryJson; const GSavedSearch({required this.id,required this.name,required this.queryJson}); }
