import 'package:flutter/material.dart';

import '../model/sheet_command.dart';
import '../model/sheet_shortcut.dart';
import '../state/sheet_sidebar_provider.dart';

class SheetCommandCatalog {
  const SheetCommandCatalog._();

  static const all = <SheetCommand>[
    SheetCommand(
      id: 'edit.undo',
      title: 'Undo',
      description: 'Revert the latest spreadsheet edit.',
      category: SheetCommandCategory.edit,
      action: SheetCommandAction.undo,
      icon: Icons.undo,
      shortcutLabel: 'Ctrl+Z',
      keywords: ['history', 'revert'],
    ),
    SheetCommand(
      id: 'edit.redo',
      title: 'Redo',
      description: 'Restore the latest undone spreadsheet edit.',
      category: SheetCommandCategory.edit,
      action: SheetCommandAction.redo,
      icon: Icons.redo,
      shortcutLabel: 'Ctrl+Y',
      keywords: ['history', 'restore'],
    ),
    SheetCommand(
      id: 'tools.quickActions',
      title: 'Quick Actions',
      description:
          'Open contextual actions for comments, links, and validation.',
      category: SheetCommandCategory.tools,
      action: SheetCommandAction.quickActions,
      icon: Icons.bolt_outlined,
      shortcutLabel: 'Fab',
      keywords: ['comment', 'hyperlink', 'validation', 'format painter'],
    ),
    SheetCommand(
      id: 'panel.shortcuts',
      title: 'Shortcuts',
      description: 'Browse supported keyboard shortcuts and navigation keys.',
      category: SheetCommandCategory.tools,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.keyboard_alt_outlined,
      shortcutLabel: SheetShortcutLabels.shortcuts,
      sidebarPanel: SheetSidebarPanel.shortcuts,
      keywords: ['keyboard', 'hotkeys', 'commands', 'guide', 'help', 'f1'],
    ),
    SheetCommand(
      id: 'view.zoomIn',
      title: 'Zoom In',
      description: 'Increase the sheet zoom level.',
      category: SheetCommandCategory.view,
      action: SheetCommandAction.zoomIn,
      icon: Icons.zoom_in,
      keywords: ['scale', 'view'],
    ),
    SheetCommand(
      id: 'view.zoomOut',
      title: 'Zoom Out',
      description: 'Decrease the sheet zoom level.',
      category: SheetCommandCategory.view,
      action: SheetCommandAction.zoomOut,
      icon: Icons.zoom_out,
      keywords: ['scale', 'view'],
    ),
    SheetCommand(
      id: 'panel.cellInspector',
      title: 'Cell Inspector',
      description: 'Edit cell value, formula, comment, and hyperlink metadata.',
      category: SheetCommandCategory.tools,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.info_outline,
      sidebarPanel: SheetSidebarPanel.cellInspector,
      keywords: ['metadata', 'comment', 'hyperlink', 'details'],
    ),
    SheetCommand(
      id: 'panel.functionLibrary',
      title: 'Function Library',
      description: 'Browse and insert spreadsheet functions.',
      category: SheetCommandCategory.formula,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.functions,
      sidebarPanel: SheetSidebarPanel.functionLibrary,
      keywords: ['formula', 'insert', 'catalog'],
    ),
    SheetCommand(
      id: 'panel.formulaAudit',
      title: 'Formula Audit',
      description: 'Trace references and dependents for the active formula.',
      category: SheetCommandCategory.formula,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.schema_outlined,
      sidebarPanel: SheetSidebarPanel.formulaAudit,
      keywords: ['trace', 'references', 'dependents'],
    ),
    SheetCommand(
      id: 'panel.formulaHealth',
      title: 'Formula Health',
      description:
          'Scan formula errors, circular references, and risky formulas.',
      category: SheetCommandCategory.formula,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.health_and_safety_outlined,
      sidebarPanel: SheetSidebarPanel.formulaHealth,
      keywords: ['errors', 'circular', 'audit'],
    ),
    SheetCommand(
      id: 'panel.goToSpecial',
      title: 'Go To Special',
      description: 'Jump to formulas, blanks, comments, links, and metadata.',
      category: SheetCommandCategory.edit,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.manage_search,
      sidebarPanel: SheetSidebarPanel.goToSpecial,
      keywords: ['find', 'select', 'navigate'],
    ),
    SheetCommand(
      id: 'panel.history',
      title: 'History',
      description: 'Review undo and redo stacks.',
      category: SheetCommandCategory.edit,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.history,
      sidebarPanel: SheetSidebarPanel.history,
      keywords: ['undo', 'redo', 'changes'],
    ),
    SheetCommand(
      id: 'panel.waraqOperations',
      title: 'Waraq Operations',
      description: 'Inspect, copy, import, and apply sheet-engine operations.',
      category: SheetCommandCategory.tools,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.hub_outlined,
      sidebarPanel: SheetSidebarPanel.sheetEngineOperations,
      keywords: ['sheet engine', 'sync', 'operation log', 'collaboration'],
    ),
    SheetCommand(
      id: 'panel.review',
      title: 'Review',
      description: 'Navigate comments and hyperlinks in the sheet.',
      category: SheetCommandCategory.review,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.rate_review_outlined,
      sidebarPanel: SheetSidebarPanel.review,
      keywords: ['comments', 'links'],
    ),
    SheetCommand(
      id: 'panel.chartBuilder',
      title: 'Chart Builder',
      description: 'Preview chart data from the selected range.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.insert_chart_outlined,
      sidebarPanel: SheetSidebarPanel.chartBuilder,
      keywords: ['visualize', 'graph', 'series'],
    ),
    SheetCommand(
      id: 'panel.namedRanges',
      title: 'Named Ranges',
      description: 'Create, update, and navigate named cell ranges.',
      category: SheetCommandCategory.formula,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.bookmarks_outlined,
      sidebarPanel: SheetSidebarPanel.namedRanges,
      keywords: ['names', 'references'],
    ),
    SheetCommand(
      id: 'panel.tables',
      title: 'Table Studio',
      description: 'Create, style, rename, and tune structured table ranges.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.table_chart_outlined,
      sidebarPanel: SheetSidebarPanel.tables,
      keywords: ['table', 'format as table', 'banded rows', 'structured data'],
    ),
    SheetCommand(
      id: 'panel.dataInsights',
      title: 'Data Insights',
      description: 'Profile selected data for quality and composition signals.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.insights,
      sidebarPanel: SheetSidebarPanel.dataInsights,
      keywords: ['profile', 'quality', 'summary'],
    ),
    SheetCommand(
      id: 'panel.dataCleanup',
      title: 'Data Cleanup',
      description: 'Trim, normalize, and remove duplicate data.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.cleaning_services_outlined,
      sidebarPanel: SheetSidebarPanel.dataCleanup,
      keywords: ['trim', 'duplicates', 'normalize'],
    ),
    SheetCommand(
      id: 'panel.findReplace',
      title: 'Find & Replace',
      description: 'Search cells and replace matching text.',
      category: SheetCommandCategory.edit,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.find_replace,
      shortcutLabel: 'Ctrl+F',
      sidebarPanel: SheetSidebarPanel.findReplace,
      keywords: ['search', 'replace'],
    ),
    SheetCommand(
      id: 'panel.sortFilter',
      title: 'Sort & Filter',
      description: 'Sort rows and apply column filters.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.filter_alt,
      shortcutLabel: SheetShortcutLabels.sortFilter,
      sidebarPanel: SheetSidebarPanel.sortFilter,
      keywords: ['filter', 'sort', 'criteria'],
    ),
    SheetCommand(
      id: 'panel.sheetView',
      title: 'Sheet View',
      description: 'Adjust freeze panes and zoom controls.',
      category: SheetCommandCategory.view,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.visibility_outlined,
      sidebarPanel: SheetSidebarPanel.sheetView,
      keywords: ['freeze', 'viewport', 'zoom'],
    ),
    SheetCommand(
      id: 'panel.conditionalFormat',
      title: 'Conditional Format',
      description: 'Add visual rules for values in the selected range.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.format_color_fill,
      sidebarPanel: SheetSidebarPanel.conditionalFormat,
      keywords: ['rules', 'highlight', 'format'],
    ),
    SheetCommand(
      id: 'panel.dataValidation',
      title: 'Data Validation',
      description: 'Restrict selected cells to valid values.',
      category: SheetCommandCategory.data,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.rule,
      sidebarPanel: SheetSidebarPanel.dataValidation,
      keywords: ['dropdown', 'rules', 'valid values'],
    ),
    SheetCommand(
      id: 'panel.performance',
      title: 'Performance',
      description: 'Inspect rendered rows, columns, and viewport metrics.',
      category: SheetCommandCategory.tools,
      action: SheetCommandAction.openSidebarPanel,
      icon: Icons.speed,
      sidebarPanel: SheetSidebarPanel.performance,
      keywords: ['viewport', 'metrics', 'render'],
    ),
  ];

  static List<SheetCommand> search(String query) {
    return [
      for (final command in all)
        if (command.matches(query)) command,
    ];
  }
}
