import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/historical_event.dart';
import '../models/timeline_view.dart';

final eventsProvider = Provider<List<HistoricalEvent>>((ref) {
  return [
    HistoricalEvent(
      id: '1',
      title: 'Moon Landing',
      date: DateTime(1969, 7, 20, 20, 17),
      description:
          'Apollo 11 mission successfully lands humans on the Moon. Neil Armstrong and Buzz Aldrin become the first humans to walk on the lunar surface, marking a historic achievement for humanity.',
      categories: [
        EventCategory.science,
        EventCategory.technology,
        EventCategory.exploration,
      ],
      imageUrl: 'https://picsum.photos/400/300?random=1',
      videoUrl: 'https://example.com/moon-landing',
      popularity: 100,
      location: 'Moon, Mare Tranquillitatis',
      quote:
          '"That\'s one small step for man, one giant leap for mankind." - Neil Armstrong',
      relatedEventIds: ['5', '7'],
      lat: 0.6875,
      lng: 23.4333,
      impactScore: 100,
      tags: ['space', 'NASA', 'cold war', 'achievement'],
      sourceUrl: 'https://nasa.gov',
    ),
    HistoricalEvent(
      id: '2',
      title: 'World War II Begins',
      date: DateTime(1939, 9, 1, 4, 45),
      description:
          'Germany invades Poland, marking the beginning of World War II in Europe. This conflict would become the deadliest in human history, involving over 30 countries and resulting in profound changes to the global order.',
      categories: [EventCategory.war, EventCategory.politics],
      imageUrl: 'https://picsum.photos/400/300?random=2',
      articleUrl: 'https://example.com/wwii',
      popularity: 95,
      location: 'Poland',
      relatedEventIds: ['4'],
      lat: 52.2297,
      lng: 21.0122,
      impactScore: 100,
      tags: ['world war', 'conflict', 'europe'],
    ),
    HistoricalEvent(
      id: '3',
      title: 'Mona Lisa Completed',
      date: DateTime(1519, 1, 1),
      description:
          'Leonardo da Vinci completes the Mona Lisa, one of the most famous paintings in the world. The enigmatic smile and masterful technique continue to captivate viewers centuries later.',
      categories: [EventCategory.art, EventCategory.culture],
      imageUrl: 'https://picsum.photos/400/300?random=3',
      popularity: 85,
      location: 'France',
      quote: '"Art is never finished, only abandoned." - Leonardo da Vinci',
      lat: 48.8606,
      lng: 2.3376,
      impactScore: 90,
      tags: ['renaissance', 'painting', 'masterpiece'],
    ),
    HistoricalEvent(
      id: '4',
      title: 'Fall of the Berlin Wall',
      date: DateTime(1989, 11, 9, 18, 53),
      description:
          'The Berlin Wall falls, symbolizing the end of the Cold War and the division of East and West Germany. Citizens celebrate as they freely cross the border for the first time in decades.',
      categories: [EventCategory.politics, EventCategory.culture],
      imageUrl: 'https://picsum.photos/400/300?random=4',
      audioUrl: 'https://example.com/berlin-wall',
      popularity: 90,
      location: 'Berlin, Germany',
      relatedEventIds: ['2'],
      lat: 52.5200,
      lng: 13.4050,
      impactScore: 95,
      tags: ['cold war', 'freedom', 'germany', 'reunification'],
    ),
    HistoricalEvent(
      id: '5',
      title: 'World Wide Web Goes Public',
      date: DateTime(1991, 8, 6, 9, 0),
      description:
          'Tim Berners-Lee releases the World Wide Web to the public at CERN, revolutionizing global communication and information sharing. This marks the beginning of the internet age as we know it.',
      categories: [
        EventCategory.technology,
        EventCategory.science,
        EventCategory.invention,
      ],
      imageUrl: 'https://picsum.photos/400/300?random=5',
      videoUrl: 'https://example.com/www',
      popularity: 98,
      location: 'CERN, Switzerland',
      relatedEventIds: ['1'],
      lat: 46.2044,
      lng: 6.1432,
      impactScore: 100,
      tags: ['internet', 'technology', 'communication', 'innovation'],
    ),
    HistoricalEvent(
      id: '6',
      title: 'Columbus Reaches Americas',
      date: DateTime(1492, 10, 12, 2, 0),
      description:
          'Christopher Columbus arrives in the Americas, beginning European exploration of the New World. This voyage would lead to unprecedented cultural exchange and transformation of world history.',
      categories: [EventCategory.exploration, EventCategory.culture],
      imageUrl: 'https://picsum.photos/400/300?random=6',
      popularity: 88,
      location: 'San Salvador, Bahamas',
      lat: 24.0633,
      lng: -74.5250,
      impactScore: 95,
      tags: ['exploration', 'discovery', 'voyage'],
    ),
    HistoricalEvent(
      id: '7',
      title: 'Discovery of Penicillin',
      date: DateTime(1928, 9, 28, 11, 0),
      description:
          'Alexander Fleming discovers penicillin by accident in his laboratory, revolutionizing medicine and saving millions of lives. This discovery marks the beginning of the antibiotic era.',
      categories: [
        EventCategory.science,
        EventCategory.technology,
        EventCategory.invention,
      ],
      imageUrl: 'https://picsum.photos/400/300?random=7',
      popularity: 92,
      location: 'London, United Kingdom',
      relatedEventIds: ['1'],
      lat: 51.5074,
      lng: -0.1278,
      impactScore: 98,
      tags: ['medicine', 'discovery', 'antibiotics', 'health'],
    ),
    HistoricalEvent(
      id: '8',
      title: 'French Revolution Begins',
      date: DateTime(1789, 7, 14, 5, 30),
      description:
          'Storming of the Bastille marks a pivotal moment in the French Revolution. This event symbolizes the uprising against tyranny and becomes a defining moment in the fight for liberty, equality, and fraternity.',
      categories: [EventCategory.politics, EventCategory.war],
      imageUrl: 'https://picsum.photos/400/300?random=8',
      popularity: 87,
      location: 'Paris, France',
      quote: '"Liberty, Equality, Fraternity"',
      lat: 48.8566,
      lng: 2.3522,
      impactScore: 92,
      tags: ['revolution', 'france', 'liberty', 'democracy'],
    ),
    HistoricalEvent(
      id: '9',
      title: 'First Olympics of Modern Era',
      date: DateTime(1896, 4, 6, 15, 0),
      description:
          'The first modern Olympic Games open in Athens, Greece, reviving the ancient tradition and establishing a global sporting event that promotes peace and unity among nations.',
      categories: [EventCategory.sports, EventCategory.culture],
      imageUrl: 'https://picsum.photos/400/300?random=9',
      popularity: 75,
      location: 'Athens, Greece',
      lat: 37.9838,
      lng: 23.7275,
      impactScore: 70,
      tags: ['olympics', 'sports', 'competition', 'unity'],
    ),
    HistoricalEvent(
      id: '10',
      title: 'Gutenberg Press Invented',
      date: DateTime(1440, 1, 1),
      description:
          'Johannes Gutenberg invents the printing press with movable type, revolutionizing the spread of knowledge and literacy across Europe and enabling the Renaissance and Reformation.',
      categories: [
        EventCategory.technology,
        EventCategory.culture,
        EventCategory.invention,
      ],
      imageUrl: 'https://picsum.photos/400/300?random=10',
      popularity: 94,
      location: 'Mainz, Germany',
      lat: 50.0000,
      lng: 8.2711,
      impactScore: 99,
      tags: ['printing', 'innovation', 'knowledge', 'literacy'],
    ),
    HistoricalEvent(
      id: '11',
      title: 'Einstein Publishes Theory of Relativity',
      date: DateTime(1905, 6, 30),
      description:
          'Albert Einstein publishes his special theory of relativity, fundamentally changing our understanding of space, time, and energy with the famous equation E=mc².',
      categories: [EventCategory.science],
      imageUrl: 'https://picsum.photos/400/300?random=11',
      popularity: 96,
      location: 'Bern, Switzerland',
      quote:
          '"Imagination is more important than knowledge." - Albert Einstein',
      lat: 46.9480,
      lng: 7.4474,
      impactScore: 97,
      tags: ['physics', 'relativity', 'einstein', 'science'],
    ),
    HistoricalEvent(
      id: '12',
      title: 'Stock Market Crash',
      date: DateTime(1929, 10, 29, 9, 30),
      description:
          'Black Tuesday - The Wall Street stock market crashes, triggering the Great Depression. The economic downturn would affect millions worldwide and reshape economic policies.',
      categories: [EventCategory.economics, EventCategory.politics],
      imageUrl: 'https://picsum.photos/400/300?random=12',
      popularity: 82,
      location: 'New York, USA',
      lat: 40.7128,
      lng: -74.0060,
      impactScore: 88,
      tags: ['economy', 'crisis', 'depression', 'finance'],
    ),
  ];
});
