import 'models/alert.dart';
import 'models/api_endpoint.dart';

final endpointsDummy = [
  ApiEndpoint(
    id: 'ep001',
    name: 'User Authentication',
    path: '/api/v1/auth',
    method: 'POST',
    requestCount: 5243,
    averageResponseTime: 120.5,
    successRate: 99.8,
    lastAccessed: '3 min ago',
    isActive: true,
    isAuthenticated: false,
    rateLimit: 200,
    timeout: '5s',
    allowedIPs: ['*'],
    customHeaders: {'X-API-Version': '1.0'},
    cachingPolicy: {'enabled': false},
  ),
  ApiEndpoint(
    id: 'ep002',
    name: 'Product Catalog',
    path: '/api/v1/products',
    method: 'GET',
    requestCount: 12532,
    averageResponseTime: 85.2,
    successRate: 100.0,
    lastAccessed: '30 sec ago',
    isActive: true,
    isAuthenticated: true,
    rateLimit: 500,
    timeout: '3s',
    allowedIPs: ['*'],
    customHeaders: {'X-API-Version': '1.0'},
    cachingPolicy: {'enabled': true, 'ttl': 300},
  ),
  ApiEndpoint(
    id: 'ep003',
    name: 'Order Processing',
    path: '/api/v1/orders',
    method: 'POST',
    requestCount: 3256,
    averageResponseTime: 230.7,
    successRate: 98.5,
    lastAccessed: '1 min ago',
    isActive: true,
    isAuthenticated: true,
    rateLimit: 100,
    timeout: '10s',
    allowedIPs: ['*'],
    customHeaders: {'X-API-Version': '1.0'},
    cachingPolicy: {'enabled': false},
  ),
  ApiEndpoint(
    id: 'ep004',
    name: 'Legacy Payment',
    path: '/api/v1/payment/legacy',
    method: 'POST',
    requestCount: 126,
    averageResponseTime: 310.2,
    successRate: 97.2,
    lastAccessed: '2 hours ago',
    isActive: false,
    isAuthenticated: true,
    rateLimit: 50,
    timeout: '15s',
    allowedIPs: ['10.0.0.0/8', '192.168.0.0/16'],
    customHeaders: {'X-API-Version': '0.9'},
    cachingPolicy: {'enabled': false},
  ),
  ApiEndpoint(
    id: 'ep005',
    name: 'User Profile',
    path: '/api/v1/users/profile',
    method: 'GET',
    requestCount: 7821,
    averageResponseTime: 92.6,
    successRate: 99.9,
    lastAccessed: '45 sec ago',
    isActive: true,
    isAuthenticated: true,
    rateLimit: 300,
    timeout: '5s',
    allowedIPs: ['*'],
    customHeaders: {'X-API-Version': '1.0'},
    cachingPolicy: {'enabled': true, 'ttl': 600},
  ),
];

final alertsDummy = [
  Alert(
    id: 'alert1',
    title: 'High Latency Detected',
    message: 'The Product Catalog API is experiencing high latency (>200ms)',
    timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
    severity: 'warning',
    isRead: false,
  ),
  Alert(
    id: 'alert2',
    title: 'Rate Limit Exceeded',
    message:
        'User Authentication API rate limit exceeded 10 times in the last hour',
    timestamp: DateTime.now().subtract(const Duration(hours: 1)),
    severity: 'warning',
    isRead: true,
  ),
  Alert(
    id: 'alert3',
    title: 'Certificate Expiring Soon',
    message: 'Iket  SSL certificate will expire in 23 days',
    timestamp: DateTime.now().subtract(const Duration(hours: 5)),
    severity: 'info',
    isRead: false,
  ),
];
