name: postfix_manager
description: Postfix Mail Server Management System v2 — Enhanced
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  go_router: ^13.2.4
  fl_chart: ^0.68.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
