import 'package:flutter/material.dart';
import 'package:tenun/tenun_core.dart';

abstract final class AreaChartSamples {
  static final Map<String, dynamic> smoothJson = {
    'type': 'area',
    'title': {'text': 'Monthly Revenue (Smooth)'},
    'xAxis': {
      'show': true,
      'data': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
      'axisLine': {
        'lineStyle': {'color': '#A0A0A0', 'width': 1.0},
      },
    },
    'yAxis': {
      'show': true,
      'precision': 0,
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'grid': {
      'show': true,
      'showHorizontalLines': true,
      'showVerticalLines': true,
      'horizontalColor': '#E8E8E8',
      'verticalColor': '#F0F0F0',
      'horizontalWidth': 0.8,
      'verticalWidth': 0.8,
    },
    'legend': {'show': true, 'textColor': '#1F1F1F', 'fontSize': 12},
    'tooltip': {
      'show': true,
      'formatter': '{a} ({b}) => {c}',
      'precision': 1,
      'textColor': '#FFFFFF',
      'backgroundColor': '#222222',
      'borderColor': '#4A90E2',
      'borderWidth': 1.0,
      'borderRadius': 8.0,
      'padding': 10.0,
      'fontSize': 12.0,
      'axisPointer': {
        'lineStyle': {'color': '#4A90E2', 'width': 1.0},
      },
    },
    'curveSmoothness': 0.25,
    'showDots': true,
    'dotSize': 4.0,
    'areaColor': '#4A90E2',
    'areaOpacity': 0.25,
    'gradientArea': true,
    'series': [
      {
        'name': 'Revenue 2024',
        'data': [120, 132, 101, 134, 90, 180],
        'color': '#4A90E2',
      },
      {
        'name': 'Revenue 2023',
        'data': [90, 110, 85, 105, 65, 150],
        'color': '#E57373',
      },
    ],
  };

  static final Map<String, dynamic> straightNoDotsJson = {
    'type': 'area',
    'title': {'text': 'Quarterly Profit (Straight + Solid)'},
    'xAxis': {
      'show': true,
      'data': ['Q1', 'Q2', 'Q3', 'Q4'],
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'yAxis': {
      'show': true,
      'precision': 0,
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'grid': {
      'show': true,
      'showHorizontalLines': true,
      'showVerticalLines': false,
      'horizontalColor': '#E6E6E6',
      'horizontalWidth': 0.8,
    },
    'legend': {'show': true, 'textColor': '#1F1F1F', 'fontSize': 12},
    'tooltip': {
      'show': true,
      'formatter': '{a}: {c}',
      'precision': 0,
      'textColor': '#FFFFFF',
      'backgroundColor': '#1E293B',
      'borderRadius': 8.0,
    },
    'curveSmoothness': 0.0,
    'showDots': false,
    'areaOpacity': 0.3,
    'gradientArea': false,
    'areaColor': '#34A853',
    'series': [
      {
        'name': 'Product A',
        'data': [120, 160, 150, 190],
        'color': '#34A853',
      },
      {
        'name': 'Product B',
        'data': [90, 110, 125, 170],
        'color': '#F59E0B',
      },
    ],
  };

  static final Map<String, dynamic> positiveNegativeJson = {
    'type': 'area',
    'title': {'text': 'Net Cashflow (Positive / Negative)'},
    'xAxis': {
      'show': true,
      'data': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'yAxis': {
      'show': true,
      'precision': 0,
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'grid': {
      'show': true,
      'showHorizontalLines': true,
      'showVerticalLines': true,
      'horizontalColor': '#ECECEC',
      'verticalColor': '#F3F3F3',
    },
    'legend': {'show': true, 'textColor': '#1F1F1F', 'fontSize': 12},
    'tooltip': {
      'show': true,
      'formatter': '{b}: {c}',
      'precision': 1,
      'textColor': '#111827',
      'backgroundColor': '#F9FAFB',
      'borderColor': '#9CA3AF',
      'borderWidth': 1.0,
      'borderRadius': 8.0,
      'axisPointer': {
        'lineStyle': {'color': '#6B7280', 'width': 1.0},
      },
    },
    'curveSmoothness': 0.2,
    'showDots': true,
    'dotSize': 3.5,
    'areaOpacity': 0.22,
    'gradientArea': true,
    'areaColor': '#8B5CF6',
    'series': [
      {
        'name': 'Cashflow',
        'data': [40, -20, 35, -10, 55, -5, 20],
        'color': '#8B5CF6',
      },
    ],
  };

  static final Map<String, dynamic> denseDailyJson = {
    'type': 'area',
    'title': {'text': 'Traffic (14 Days)'},
    'xAxis': {
      'show': true,
      'data': [
        'D1',
        'D2',
        'D3',
        'D4',
        'D5',
        'D6',
        'D7',
        'D8',
        'D9',
        'D10',
        'D11',
        'D12',
        'D13',
        'D14',
      ],
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'yAxis': {
      'show': true,
      'precision': 0,
      'fontSize': 10,
      'color': '#666666',
      'axisLabel': {'show': true},
    },
    'grid': {
      'show': true,
      'showHorizontalLines': true,
      'showVerticalLines': true,
      'horizontalColor': '#E9E9E9',
      'verticalColor': '#F4F4F4',
      'horizontalWidth': 0.6,
      'verticalWidth': 0.6,
    },
    'legend': {'show': true, 'textColor': '#1F1F1F', 'fontSize': 12},
    'tooltip': {
      'show': true,
      'formatter': '{a} [{b}] = {c}',
      'precision': 0,
      'textColor': '#FFFFFF',
      'backgroundColor': '#0F172A',
      'borderRadius': 8.0,
    },
    'curveSmoothness': 0.3,
    'showDots': false,
    'dotSize': 3.0,
    'areaOpacity': 0.2,
    'gradientArea': true,
    'areaColor': '#06B6D4',
    'series': [
      {
        'name': 'Visitors',
        'data': [
          80,
          95,
          90,
          110,
          120,
          130,
          125,
          140,
          155,
          150,
          162,
          170,
          165,
          178,
        ],
        'color': '#06B6D4',
      },
      {
        'name': 'Conversions',
        'data': [20, 30, 25, 35, 42, 44, 38, 48, 52, 49, 58, 62, 59, 67],
        'color': '#EF4444',
      },
    ],
  };

  static final AreaChartConfig configObject = AreaChartConfig(
    title: TitlesData(text: 'Monthly Revenue (Config Object)'),
    xAxis: XYAxis(data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']),
    yAxis: XYAxis(precision: 0),
    series: [
      Series(
        type: ChartType.area,
        name: 'Revenue 2024',
        data: [120, 132, 101, 134, 90, 180],
        color: const Color(0xFF4A90E2),
      ),
      Series(
        type: ChartType.area,
        name: 'Revenue 2023',
        data: [90, 110, 85, 105, 65, 150],
        color: const Color(0xFFE57373),
      ),
    ],
    curveSmoothness: 0.25,
    showDots: true,
    dotSize: 4.0,
    areaColor: '#4A90E2',
    areaOpacity: 0.25,
    gradientArea: true,
    legend: ChartLegend(show: true),
    tooltip: ChartTooltip(
      show: true,
      formatter: '{a} ({b}) => {c}',
      precision: 1,
      textColor: '#FFFFFF',
      backgroundColor: '#222222',
    ),
    grid: GridData(
      show: true,
      showHorizontalLines: true,
      showVerticalLines: true,
    ),
  );
}
