import 'package:flutter/material.dart';
import 'package:tenun_pro/tenun_pro.dart' hide FontWeight;

import 'simple_charts_showcase_data.dart';
import 'simple_charts_showcase_gallery_options.dart';
import 'simple_charts_showcase_statistical_sources.dart';
import 'simple_charts_showcase_widgets.dart';

List<Widget> simpleChartsStatisticalPanels(
  SimpleChartsGalleryOptions options,
) => [
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Activity Heatmap',
    subtitle: 'Intensity by time and day',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.activityHeatmap,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleHeatmapChart(
      xLabels: SimpleChartsShowcaseData.activityDays,
      yLabels: SimpleChartsShowcaseData.activitySegments,
      cells: SimpleChartsShowcaseData.activityHeatmap,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveCell: options.showActiveBars,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Activity Punch Card',
    subtitle: 'Dot intensity by time and day',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.activityPunchCard,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimplePunchCardChart(
      xLabels: SimpleChartsShowcaseData.activityDays,
      yLabels: SimpleChartsShowcaseData.activitySegments,
      cells: SimpleChartsShowcaseData.activityPunchCards,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveDot: options.showActiveBars,
      useColorScale: options.showReferenceBands,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Activity Radial Heatmap',
    subtitle: 'Cyclical intensity by ring and segment',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.activityRadialHeatmap,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleRadialHeatmapChart(
      ringLabels: SimpleChartsShowcaseData.activitySegments,
      segmentLabels: SimpleChartsShowcaseData.activityDays,
      cells: SimpleChartsShowcaseData.activityRadialHeatmap,
      style: options.barStyle,
      showGrid: options.showGrid,
      showRingLabels: options.showValues,
      showSegmentLabels: options.showReferenceLines,
      showValues: options.showReferenceBands,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveCell: options.showActiveBars,
      showCenterHole: options.showTracks,
      innerRadiusFactor: options.showReferenceBands ? 0.28 : 0.2,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Metric Correlation',
    subtitle: 'Pairwise relationship matrix',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.metricCorrelation,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleCorrelationMatrixChart(
      variables: SimpleChartsShowcaseData.capabilityCorrelationVariables,
      correlations: SimpleChartsShowcaseData.capabilityCorrelations,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveCell: options.showActiveBars,
      showDiagonal: options.showTracks,
      showUpperTriangleOnly: options.showReferenceBands,
      valueFormatter: (value) => value.toStringAsFixed(2),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Capability Scatter Matrix',
    subtitle: 'Pairwise numeric relationships',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.capabilityScatterMatrix,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleScatterPlotMatrixChart(
      variableLabels: const ['Speed', 'Quality', 'Cost', 'Risk'],
      points: SimpleChartsShowcaseData.capabilityScatterMatrix,
      style: options.barStyle,
      minValues: const [0, 0, 0, 0],
      maxValues: const [100, 100, 100, 100],
      showGrid: options.showGrid,
      showDiagonalHistograms: options.showReferenceBands,
      showVariableLabels: true,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActivePoint: options.showActiveBars,
      pointRadius: options.showReferenceBands ? 3.8 : 3.2,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Regional Tile Map',
    subtitle: 'Map-like comparison without polygons',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.regionalTileMap,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleTileMapChart(
      data: SimpleChartsShowcaseData.regionalTileMap,
      style: options.barStyle,
      rows: 3,
      columns: 4,
      shape: options.showReferenceBands
          ? SimpleTileMapShape.hexagon
          : SimpleTileMapShape.rounded,
      showLabels: true,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveTile: options.showActiveBars,
      showEmptyTiles: options.showTracks,
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Usage Density',
    subtitle: 'Dense observations binned by hex cells',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.usageDensity,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleHexbinChart(
      points: SimpleChartsShowcaseData.usageDensityPoints,
      style: options.barStyle,
      minX: 0,
      maxX: 100,
      minY: 0,
      maxY: 100,
      xAxisLabel: 'Activity',
      yAxisLabel: 'Outcome',
      cellRadius: options.showReferenceBands ? 15 : 17,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showAxisLabels: options.showReferenceLines,
      showEmptyBins: options.showTracks,
      showTooltip: options.showTooltips,
      showActiveBin: options.showActiveBars,
      useLogScale: options.showReferenceBands,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Usage Heat Grid',
    subtitle: 'Continuous observations in rectangular bins',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.usageHeatGrid,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleContinuousHeatmapChart(
      points: SimpleChartsShowcaseData.usageHeatmapPoints,
      style: options.barStyle,
      minX: 0,
      maxX: 100,
      minY: 0,
      maxY: 100,
      xBins: options.showReferenceBands ? 7 : 6,
      yBins: options.showReferenceBands ? 6 : 5,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveCell: options.showActiveBars,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Service Territories',
    subtitle: 'Nearest-site coverage regions',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.serviceTerritories,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleVoronoiChart(
      sites: SimpleChartsShowcaseData.serviceTerritories,
      style: options.barStyle,
      minX: 0,
      maxX: 100,
      minY: 0,
      maxY: 100,
      xAxisLabel: 'Reach',
      yAxisLabel: 'Demand',
      showGrid: options.showGrid,
      showLabels: options.showValues,
      showValues: options.showReferenceLines,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveCell: options.showActiveBars,
      showAxisLabels: options.showReferenceLines,
      showBoundaries: options.showTracks,
      regionOpacity: options.showReferenceBands ? 0.34 : 0.24,
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Performance Contours',
    subtitle: 'Interpolated surface and isolines',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.performanceContours,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleContourChart(
      points: SimpleChartsShowcaseData.performanceSurface,
      style: options.barStyle,
      minX: 0,
      maxX: 100,
      minY: 0,
      maxY: 100,
      xAxisLabel: 'Reach',
      yAxisLabel: 'Demand',
      gridResolution: options.showReferenceBands ? 30 : 24,
      levelCount: options.showReferenceLines ? 7 : 6,
      showGrid: options.showGrid,
      showFilledBands: true,
      showContourLines: options.showReferenceLines,
      showSamplePoints: options.showTracks,
      showLabels: options.showValues,
      showValues: options.showReferenceBands,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveSelection: options.showActiveBars,
      showAxisLabels: options.showReferenceLines,
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Capability Parallel',
    subtitle: 'Multivariate profile comparison',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.capabilityParallel,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleParallelCoordinatesChart(
      axes: SimpleChartsShowcaseData.capabilityParallelAxes,
      series: SimpleChartsShowcaseData.capabilityParallel,
      style: options.barStyle,
      showGrid: options.showGrid,
      showLabels: true,
      showValues: options.showValues,
      showAxisRangeLabels: options.showReferenceLines,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveSeries: options.showActiveBars,
      lineOpacity: options.showReferenceBands ? 0.5 : 0.36,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Learning Calendar',
    subtitle: 'Daily intensity across a quarter',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.learningCalendar,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleCalendarHeatmapChart(
      data: SimpleChartsShowcaseData.learningCalendar,
      startDate: DateTime(2026, 1),
      endDate: DateTime(2026, 3, 31),
      style: options.barStyle,
      showMonthLabels: true,
      showWeekdayLabels: options.showReferenceLines,
      showValues: false,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveDay: options.showActiveBars,
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Distribution',
    subtitle: 'Frequency buckets and spread',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreDistribution,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleHistogramChart(
      values: SimpleChartsShowcaseData.scoreDistribution,
      binCount: 8,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showMean: options.showReferenceLines,
      showMedian: options.showReferenceLines,
      showDistributionCurve: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveBin: options.showActiveBars,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Binned Dots',
    subtitle: 'Distribution as stacked observations',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreBinnedDots,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleBinnedDotPlotChart(
      values: SimpleChartsShowcaseData.scoreDistribution,
      binCount: 8,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showAxisLabels: true,
      showTooltip: options.showTooltips,
      showActiveBin: options.showActiveBars,
      dotValue: options.showReferenceBands ? 1 : 2,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Frequency Polygon',
    subtitle: 'Connected frequency buckets',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreFrequencyPolygon,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleFrequencyPolygonChart(
      values: SimpleChartsShowcaseData.scoreDistribution,
      binCount: 8,
      style: options.trendStyle,
      minValue: 0,
      maxValue: 100,
      minFrequency: 0,
      scale: options.showReferenceBands
          ? SimpleFrequencyPolygonScale.percent
          : SimpleFrequencyPolygonScale.count,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showDots: options.showTracks,
      showArea: options.showReferenceBands,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 4, label: 'Count')]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
      frequencyFormatter: (value) => options.showReferenceBands
          ? '${value.toStringAsFixed(0)}%'
          : value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Density',
    subtitle: 'Smoothed distribution comparison',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreDensity,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleDensityChart(
      series: SimpleChartsShowcaseData.scoreDensity,
      style: options.trendStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showArea: options.showReferenceBands,
      showRug: options.showTracks,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveSeries: options.showActiveBars,
      showMean: options.showReferenceLines,
      showMedian: options.showReferenceLines,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF6366F1),
              ),
            ]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Raincloud',
    subtitle: 'Density, box summary, and samples',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreRaincloud,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleRaincloudChart(
      data: SimpleChartsShowcaseData.scoreRaincloud,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showCloud: options.showReferenceBands,
      showBox: options.showTracks,
      showDots: options.showTracks,
      showMean: options.showReferenceLines,
      showOutliers: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveGroup: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Response ECDF',
    subtitle: 'Cumulative share under threshold',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.responseEcdf,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleEcdfChart(
      series: SimpleChartsShowcaseData.responseEcdf,
      style: options.trendStyle,
      minValue: 0,
      maxValue: 120,
      showGrid: options.showGrid,
      showDots: options.showTracks,
      showValues: options.showValues,
      showArea: options.showReferenceBands,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActivePoint: options.showActiveBars,
      showMedianLine: options.showReferenceLines,
      showP90Line: options.showReferenceBands,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 90, label: 'SLA')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 0,
                to: 60,
                label: 'Fast',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => '${value.toStringAsFixed(0)} ms',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score QQ Plot',
    subtitle: 'Quantile comparison against baseline',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreQQPlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleQQPlotChart(
      series: SimpleChartsShowcaseData.scoreQQPlot,
      style: options.barStyle,
      minX: 30,
      maxX: 100,
      minY: 30,
      maxY: 100,
      xAxisLabel: 'Control quantile',
      yAxisLabel: 'Program quantile',
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActivePoint: options.showActiveBars,
      showReferenceLine: options.showReferenceLines,
      showFitLine: options.showReferenceBands,
      xValueFormatter: (value) => value.toStringAsFixed(0),
      yValueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Concentration Lorenz',
    subtitle: 'Cumulative share and Gini balance',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.concentrationLorenz,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleLorenzCurveChart(
      series: SimpleChartsShowcaseData.concentrationLorenz,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActivePoint: options.showActiveBars,
      showEqualityLine: options.showReferenceLines,
      showArea: options.showReferenceBands,
      showGini: options.showReferenceLines,
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Measurement Agreement',
    subtitle: 'Bias and limits between two methods',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.measurementAgreement,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleBlandAltmanChart(
      points: SimpleChartsShowcaseData.measurementAgreement,
      style: options.barStyle,
      minMean: 60,
      maxMean: 95,
      minDifference: -4,
      maxDifference: 6,
      methodALabel: 'Baseline',
      methodBLabel: 'Review',
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActivePoint: options.showActiveBars,
      showBiasLine: options.showReferenceLines,
      showAgreementLimits: options.showReferenceLines,
      showAgreementBand: options.showReferenceBands,
      showZeroLine: options.showTracks,
      highlightOutliers: options.showReferenceBands,
      meanFormatter: (value) => value.toStringAsFixed(0),
      differenceFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Spread',
    subtitle: 'Median, quartiles, and outliers',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreSpread,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleBoxPlotChart(
      data: SimpleChartsShowcaseData.scoreSpread,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showMean: options.showReferenceLines,
      showOutliers: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveBox: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Boxen Plot',
    subtitle: 'Nested quantile bands and tails',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreBoxenPlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleBoxenPlotChart(
      data: SimpleChartsShowcaseData.scoreBoxen,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      maxDepth: options.showReferenceBands ? 4 : 3,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showMedian: true,
      showWhiskers: options.showTracks,
      showTooltip: options.showTooltips,
      showActiveBox: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Shape',
    subtitle: 'Distribution density by cohort',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreShape,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleViolinChart(
      data: SimpleChartsShowcaseData.scoreShape,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showBoxPlot: options.showTracks,
      showMean: options.showReferenceLines,
      showOutliers: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveViolin: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF6366F1),
              ),
            ]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Cohort Ridgelines',
    subtitle: 'Stacked distribution shape',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.cohortRidgelines,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleRidgelineChart(
      data: SimpleChartsShowcaseData.cohortRidges,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showBaseline: options.showTracks,
      showMedian: options.showReferenceLines,
      showMean: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveRidge: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Score Rug Plot',
    subtitle: 'Raw observations along an axis',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.scoreRugPlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleRugPlotChart(
      series: SimpleChartsShowcaseData.scoreRugs,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLabels: true,
      showLegend: options.showLegends,
      showBaseline: options.showTracks,
      showMedian: options.showReferenceLines,
      showTooltip: options.showTooltips,
      showActiveTick: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Response Barcode Plot',
    subtitle: 'Event density along a scale',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.responseBarcodePlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleBarcodePlotChart(
      series: SimpleChartsShowcaseData.responseBarcode,
      style: options.barStyle,
      minValue: 0,
      maxValue: 120,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showLabels: true,
      showLegend: options.showLegends,
      showBaseline: options.showTracks,
      showMedian: options.showReferenceLines,
      showTooltip: options.showTooltips,
      showActiveTick: options.showActiveBars,
      tickLength: options.showReferenceBands ? 30 : 24,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 90, label: 'SLA')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 0,
                to: 60,
                label: 'Fast',
                color: Color(0xFF2563EB),
              ),
            ]
          : const [],
      valueFormatter: (value) => '${value.toStringAsFixed(0)} ms',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Sample Strip Plot',
    subtitle: 'Every observation by cohort',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.sampleStripPlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleStripPlotChart(
      data: SimpleChartsShowcaseData.sampleStrips,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showMean: options.showReferenceLines,
      showMedian: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveDot: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF6366F1),
              ),
            ]
          : const [],
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Sample Sina Plot',
    subtitle: 'Density-shaped observations',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.sampleSinaPlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleSinaPlotChart(
      data: SimpleChartsShowcaseData.sampleSina,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showMean: options.showReferenceLines,
      showMedian: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveDot: options.showActiveBars,
      densitySpreadFactor: options.showReferenceBands ? 0.88 : 0.72,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF7C3AED),
              ),
            ]
          : const [],
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Sample Beeswarm',
    subtitle: 'Packed observations without overlap',
    source: simpleStatisticalSampleSource(
      SimpleStatisticalSampleSourceKey.sampleBeeswarm,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleBeeswarmChart(
      data: SimpleChartsShowcaseData.sampleBeeswarm,
      style: options.barStyle,
      minValue: 0,
      maxValue: 100,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showMean: options.showReferenceLines,
      showMedian: options.showReferenceBands,
      showTooltip: options.showTooltips,
      showActiveDot: options.showActiveBars,
      referenceLines: options.showReferenceLines
          ? const [SimpleChartReferenceLine(value: 75, label: 'Goal')]
          : const [],
      referenceBands: options.showReferenceBands
          ? const [
              SimpleChartReferenceBand(
                from: 70,
                to: 90,
                label: 'Target',
                color: Color(0xFF14B8A6),
              ),
            ]
          : const [],
      valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
    ),
  ),
];
