import 'package:flutter/material.dart';
import 'package:tenun_pro/tenun_pro.dart' hide FontWeight;

import 'simple_charts_showcase_comparison_sources.dart';
import 'simple_charts_showcase_data.dart';
import 'simple_charts_showcase_gallery_options.dart';
import 'simple_charts_showcase_widgets.dart';

List<Widget> simpleChartsComparisonPanels(SimpleChartsGalleryOptions options) =>
    [
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Priority Pareto',
        subtitle: 'Ranked drivers and cumulative share',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.priorityPareto,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleParetoChart(
          data: SimpleChartsShowcaseData.priorityPareto,
          style: options.barStyle,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showCumulativeLabels: options.showReferenceLines,
          showTargetLine: options.showReferenceBands,
          showTooltip: options.showTooltips,
          showActiveItem: options.showActiveBars,
          valueFormatter: (value) => value.toStringAsFixed(0),
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Forecast Range',
        subtitle: 'Min, max, and expected value',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.forecastRange,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleRangeChart(
          data: SimpleChartsShowcaseData.forecastRanges,
          style: options.barStyle,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showRangeLabels: options.showValues,
          showMarkers: options.showTracks,
          showTooltip: options.showTooltips,
          showActiveRange: options.showActiveBars,
          referenceLines: options.showReferenceLines
              ? const [SimpleChartReferenceLine(value: 75, label: 'Plan')]
              : const [],
          referenceBands: options.showReferenceBands
              ? const [
                  SimpleChartReferenceBand(
                    from: 70,
                    to: 90,
                    label: 'Target Zone',
                    color: Color(0xFF22C55E),
                  ),
                ]
              : const [],
          valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Sensitivity Tornado',
        subtitle: 'Low and high scenario impact',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.sensitivityTornado,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleTornadoChart(
          data: SimpleChartsShowcaseData.sensitivityTornado,
          baseline: 72,
          lowLabel: 'Low case',
          highLabel: 'High case',
          style: options.barStyle,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showLegend: options.showLegends,
          showBaseline: options.showReferenceLines,
          showTooltip: options.showTooltips,
          showActiveBar: options.showActiveBars,
          valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Experiment Error Bars',
        subtitle: 'Mean and confidence interval',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.experimentErrorBars,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleErrorBarChart(
          data: SimpleChartsShowcaseData.experimentIntervals,
          style: options.barStyle,
          minValue: 50,
          maxValue: 100,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showErrorLabels: options.showReferenceLines,
          showCaps: options.showTracks,
          showLine: options.showReferenceBands,
          showTooltip: options.showTooltips,
          showActivePoint: options.showActiveBars,
          referenceLines: options.showReferenceLines
              ? const [SimpleChartReferenceLine(value: 75, label: 'Plan')]
              : const [],
          referenceBands: options.showReferenceBands
              ? const [
                  SimpleChartReferenceBand(
                    from: 70,
                    to: 90,
                    label: 'Confidence',
                    color: Color(0xFF6366F1),
                  ),
                ]
              : const [],
          valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Experiment Forest',
        subtitle: 'Effect size and confidence interval',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.experimentForest,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleForestPlotChart(
          data: SimpleChartsShowcaseData.experimentEffects,
          style: options.barStyle,
          minValue: -0.4,
          maxValue: 0.4,
          referenceValue: 0,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showIntervalLabels: options.showReferenceLines,
          showWeights: options.showReferenceBands,
          showReferenceLine: options.showReferenceLines,
          showTooltip: options.showTooltips,
          showActiveItem: options.showActiveBars,
          referenceBands: options.showReferenceBands
              ? const [
                  SimpleChartReferenceBand(
                    from: 0,
                    to: 0.4,
                    label: 'Positive',
                    color: Color(0xFF22C55E),
                  ),
                ]
              : const [],
          valueFormatter: (value) => value.toStringAsFixed(2),
          weightFormatter: (value) => '${value.toStringAsFixed(0)}%',
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Benchmark Dots',
        subtitle: 'Compact ranking and comparison',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.benchmarkDots,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleDotPlotChart(
          categories: SimpleChartsShowcaseData.benchmarkCategories,
          series: SimpleChartsShowcaseData.benchmarkDots,
          style: options.barStyle,
          minValue: 0,
          maxValue: 100,
          showGrid: options.showGrid,
          showGuideLines: options.showReferenceLines,
          showValues: options.showValues,
          showLegend: options.showLegends,
          showTooltip: options.showTooltips,
          showActiveDot: options.showActiveBars,
          referenceLines: options.showReferenceLines
              ? const [SimpleChartReferenceLine(value: 80, label: 'Goal')]
              : const [],
          referenceBands: options.showReferenceBands
              ? const [
                  SimpleChartReferenceBand(
                    from: 75,
                    to: 90,
                    label: 'Strong',
                    color: Color(0xFF14B8A6),
                  ),
                ]
              : const [],
          valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Feedback Likert',
        subtitle: 'Diverging response distribution',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.feedbackLikert,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleLikertChart(
          categories: SimpleChartsShowcaseData.feedbackLikertCategories,
          items: SimpleChartsShowcaseData.feedbackLikert,
          style: options.barStyle,
          stackAsPercent: options.stackAsPercent,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showLegend: options.showLegends,
          showTooltip: options.showTooltips,
          showActiveSegment: options.showActiveBars,
          showCenterLine: options.showReferenceLines,
          showAxisLabels: options.showReferenceLines,
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Priority Race',
        subtitle: 'Rank movement over time',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.priorityRace,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleBumpChart(
          periods: SimpleChartsShowcaseData.priorityPeriods,
          series: SimpleChartsShowcaseData.priorityRanks,
          style: options.trendStyle,
          showGrid: options.showGrid,
          showDots: options.showTracks,
          showValues: options.showValues,
          showLegend: options.showLegends,
          showTooltip: options.showTooltips,
          showActiveSeries: options.showActiveBars,
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Roadmap Timeline',
        subtitle: 'Milestones and planned releases',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.roadmapTimeline,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleTimelineChart(
          events: SimpleChartsShowcaseData.roadmapTimeline,
          style: options.barStyle,
          alternating: options.showReferenceBands,
          showDates: options.showValues,
          showDescriptions: options.showReferenceLines,
          showTags: options.showTracks,
          showTooltip: options.showTooltips,
          showActiveEvent: options.showActiveBars,
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Milestone Roadmap',
        subtitle: 'Date-positioned gates and checkpoints',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.milestoneRoadmap,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleMilestoneChart(
          milestones: SimpleChartsShowcaseData.roadmapMilestones,
          style: options.barStyle,
          minDate: DateTime(2026, 1),
          maxDate: DateTime(2026, 5),
          alternating: options.showReferenceBands,
          showDates: options.showValues,
          showDescriptions: options.showReferenceLines,
          showTags: options.showTracks,
          showConnector: options.showGrid,
          showTooltip: options.showTooltips,
          showActiveMilestone: options.showActiveBars,
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Event Strip',
        subtitle: 'Activity density by time and lane',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.eventStrip,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleEventStripChart(
          lanes: SimpleChartsShowcaseData.eventStrip,
          style: options.barStyle,
          minDate: DateTime(2026, 1),
          maxDate: DateTime(2026, 5),
          markerDate: options.showReferenceLines ? DateTime(2026, 3, 1) : null,
          showGrid: options.showGrid,
          showDates: options.showValues,
          showEventLabels: options.showReferenceBands,
          showWeights: options.showValues,
          showMarkerDate: options.showReferenceLines,
          showTooltip: options.showTooltips,
          showActiveEvent: options.showActiveBars,
          weightFormatter: (value) => value.toStringAsFixed(1),
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Project Gantt',
        subtitle: 'Task duration, dependencies, progress',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.projectGantt,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleGanttChart(
          tasks: SimpleChartsShowcaseData.projectGantt,
          style: options.barStyle,
          minDate: DateTime(2026, 1),
          maxDate: DateTime(2026, 3, 5),
          today: options.showReferenceLines ? DateTime(2026, 2) : null,
          showGrid: options.showGrid,
          showDates: options.showValues,
          showProgress: options.showValues,
          showDependencies: options.showReferenceBands,
          showToday: options.showReferenceLines,
          showTooltip: options.showTooltips,
          showActiveTask: options.showActiveBars,
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Before / After Slope',
        subtitle: 'Two-point movement comparison',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.beforeAfterSlope,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimpleSlopeChart(
          data: SimpleChartsShowcaseData.slopeMoves,
          startLabel: 'Before',
          endLabel: 'After',
          style: options.trendStyle,
          minValue: 0,
          maxValue: 100,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showDelta: options.showReferenceLines,
          showEndLabels: true,
          showTooltip: options.showTooltips,
          showActiveLine: options.showActiveBars,
          valueFormatter: (value) => '${value.toStringAsFixed(0)} pts',
        ),
      ),
      SimpleChartsShowcasePanel(
        width: options.panelWidth,
        title: 'Cohort Pyramid',
        subtitle: 'Two-sided segment distribution',
        source: simpleComparisonSampleSource(
          SimpleComparisonSampleSourceKey.cohortPyramid,
          options,
        ),
        showSampleJson: options.showSampleJson,
        showSampleCode: options.showSampleCode,
        child: SimplePopulationPyramidChart(
          data: SimpleChartsShowcaseData.cohortPyramid,
          leftLabel: 'Learners',
          rightLabel: 'Mentors',
          style: options.barStyle,
          showGrid: options.showGrid,
          showValues: options.showValues,
          showLegend: options.showLegends,
          showTooltip: options.showTooltips,
          showActiveBar: options.showActiveBars,
          valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
        ),
      ),
    ];
