import 'package:flutter/material.dart';
import 'package:tenun_pro/tenun_pro.dart' hide FontWeight;

import 'simple_charts_showcase_composition_sources.dart';
import 'simple_charts_showcase_data.dart';
import 'simple_charts_showcase_gallery_options.dart';
import 'simple_charts_showcase_widgets.dart';

List<Widget> simpleChartsCompositionPanels(
  SimpleChartsGalleryOptions options,
) => [
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Portfolio Share',
    subtitle: 'Countable part-to-whole composition',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.portfolioShare,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleWaffleChart(
      data: SimpleChartsShowcaseData.portfolioShare,
      style: options.barStyle,
      showLegend: options.showLegends,
      showValues: options.showValues,
      showTooltip: options.showTooltips,
      showActiveCells: options.showActiveBars,
      showEmptyCells: options.showTracks,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Readiness Dot Density',
    subtitle: 'Unit dots for countable status mix',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.readinessDotDensity,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleDotDensityChart(
      data: SimpleChartsShowcaseData.readinessDots,
      totalValue: 100,
      rows: 5,
      columns: 10,
      style: options.barStyle,
      showLegend: options.showLegends,
      showValues: options.showValues,
      showTooltip: options.showTooltips,
      showActiveDots: options.showActiveBars,
      showEmptyDots: options.showTracks,
      fillDirection: options.showReferenceBands
          ? SimpleDotDensityFillDirection.leftToRight
          : SimpleDotDensityFillDirection.bottomToTop,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Packed Portfolio',
    subtitle: 'Part-to-whole magnitude clusters',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.packedPortfolio,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimplePackedBubbleChart(
      data: SimpleChartsShowcaseData.portfolioPackedBubbles,
      style: options.barStyle,
      showLegend: options.showLegends,
      showLabels: options.showValues,
      showValues: options.showValues,
      showTooltip: options.showTooltips,
      showActiveBubble: options.showActiveBars,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Strategy Ternary',
    subtitle: 'Three-way balance and tradeoff map',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.strategyTernary,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleTernaryChart(
      points: SimpleChartsShowcaseData.strategyTernary,
      style: options.barStyle,
      aAxisLabel: 'Speed',
      bAxisLabel: 'Quality',
      cAxisLabel: 'Cost',
      showGrid: options.showGrid,
      showPointLabels: options.showValues,
      showValues: options.showReferenceLines,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActivePoint: options.showActiveBars,
      gridLineCount: options.showReferenceBands ? 5 : 4,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Voice Themes',
    subtitle: 'Qualitative signal frequency',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.voiceThemes,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleWordCloudChart(
      words: SimpleChartsShowcaseData.voiceThemes,
      style: options.barStyle,
      shape: options.showReferenceBands
          ? SimpleWordCloudShape.oval
          : SimpleWordCloudShape.cloud,
      showValues: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveWord: options.showActiveBars,
      allowRotation: options.showTracks,
      maxWords: options.showReferenceLines ? 12 : 10,
      valueFormatter: (value) => value.toStringAsFixed(0),
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Audience Overlap',
    subtitle: 'Set membership and shared segments',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.audienceOverlap,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleVennChart(
      sets: SimpleChartsShowcaseData.audienceVennSets,
      intersections: SimpleChartsShowcaseData.audienceVennIntersections,
      style: options.barStyle,
      showLabels: true,
      showValues: options.showValues,
      showIntersectionLabels: options.showReferenceLines,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveRegion: options.showActiveBars,
      fillOpacity: options.showReferenceBands ? 0.28 : 0.2,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Audience UpSet',
    subtitle: 'Ranked set intersections',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.audienceUpset,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleUpsetChart(
      sets: SimpleChartsShowcaseData.audienceUpsetSets,
      intersections: SimpleChartsShowcaseData.audienceUpsetIntersections,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showSetTotals: options.showValues,
      showIntersectionLabels: options.showReferenceLines,
      showTooltip: options.showTooltips,
      showActiveIntersection: options.showActiveBars,
      maxIntersections: options.showReferenceBands ? null : 6,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Portfolio Treemap',
    subtitle: 'Nested part-to-whole allocation',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.portfolioTreemap,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleTreemapChart(
      data: SimpleChartsShowcaseData.portfolioTreemap,
      style: options.barStyle,
      showLabels: options.showValues,
      showValues: options.showValues,
      showParentLabels: options.showReferenceLines,
      showTooltip: options.showTooltips,
      showActiveTile: options.showActiveBars,
      maxDepth: options.showReferenceBands ? 3 : 2,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Portfolio Sunburst',
    subtitle: 'Radial nested allocation',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.portfolioSunburst,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleSunburstChart(
      data: SimpleChartsShowcaseData.portfolioSunburst,
      style: options.barStyle,
      centerLabel: 'Portfolio',
      showLabels: options.showValues,
      showValues: options.showValues,
      showParentLabels: options.showReferenceLines,
      showTooltip: options.showTooltips,
      showActiveSegment: options.showActiveBars,
      maxDepth: options.showReferenceBands ? 3 : 2,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Portfolio Icicle',
    subtitle: 'Hierarchy depth bands',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.portfolioIcicle,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleIcicleChart(
      data: SimpleChartsShowcaseData.portfolioIcicle,
      style: options.barStyle,
      orientation: options.showReferenceBands
          ? SimpleIcicleOrientation.horizontal
          : SimpleIcicleOrientation.vertical,
      showLabels: options.showValues,
      showValues: options.showValues,
      showParentLabels: options.showReferenceLines,
      showTooltip: options.showTooltips,
      showActiveSegment: options.showActiveBars,
      maxDepth: options.showTracks ? 4 : 3,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Portfolio Tree',
    subtitle: 'Readable hierarchy branches',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.portfolioTree,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleTreeDiagramChart(
      data: SimpleChartsShowcaseData.portfolioTree,
      style: options.barStyle,
      orientation: options.showReferenceBands
          ? SimpleTreeDiagramOrientation.horizontal
          : SimpleTreeDiagramOrientation.vertical,
      showLabels: true,
      showValues: options.showValues,
      showRoot: options.showTracks,
      showTooltip: options.showTooltips,
      showActiveNode: options.showActiveBars,
      curvedLinks: options.showReferenceLines,
      maxDepth: options.showReferenceBands ? 3 : 4,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Readiness Icons',
    subtitle: 'Countable icon array composition',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.readinessIcons,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimplePictogramChart(
      data: SimpleChartsShowcaseData.readinessIcons,
      totalValue: 100,
      rows: 5,
      columns: 10,
      style: options.barStyle,
      symbol: SimplePictogramSymbol.person,
      showLegend: options.showLegends,
      showValues: options.showValues,
      showTooltip: options.showTooltips,
      showActiveUnits: options.showActiveBars,
      showEmptyUnits: options.showTracks,
      valueFormatter: (value) => '${value.toStringAsFixed(0)}%',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Market Mosaic',
    subtitle: 'Segment size and channel mix',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.marketMosaic,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleMarimekkoChart(
      categories: SimpleChartsShowcaseData.marketMosaicCategories,
      series: SimpleChartsShowcaseData.marketMosaic,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showPercentages: options.showValues,
      showSegmentLabels: options.showReferenceLines,
      showColumnTotals: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveSegment: options.showActiveBars,
      valueFormatter: (value) => '\$${value.toStringAsFixed(0)}k',
    ),
  ),
  SimpleChartsShowcasePanel(
    width: options.panelWidth,
    title: 'Channel Mosaic Plot',
    subtitle: 'Cell-based categorical relationship',
    source: simpleCompositionSampleSource(
      SimpleCompositionSampleSourceKey.channelMosaicPlot,
      options,
    ),
    showSampleJson: options.showSampleJson,
    showSampleCode: options.showSampleCode,
    child: SimpleMosaicPlotChart(
      xLabels: SimpleChartsShowcaseData.marketMosaicCategories,
      yLabels: const ['Online', 'Partner', 'Field'],
      cells: SimpleChartsShowcaseData.marketMosaicPlot,
      style: options.barStyle,
      showGrid: options.showGrid,
      showValues: options.showValues,
      showPercentages: options.showValues,
      showCellLabels: options.showReferenceLines,
      showColumnTotals: options.showValues,
      showLegend: options.showLegends,
      showTooltip: options.showTooltips,
      showActiveCell: options.showActiveBars,
      valueFormatter: (value) => '\$${value.toStringAsFixed(0)}k',
    ),
  ),
];
