import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'widgets/billing_product_workspace_screen.dart';

export 'models/billing_cart_item.dart';
export 'models/billing_business_domain_module.dart';
export 'models/billing_business_domain_navigation_policy.dart';
export 'models/billing_business_domain_profile.dart';
export 'models/billing_business_domain_screen_registry.dart';
export 'models/billing_checkout.dart';
export 'models/billing_invoice_line_item_adapter.dart';
export 'models/billing_invoice_line_item.dart';
export 'models/billing_invoice_issue_command.dart';
export 'models/billing_invoice_issue_policy.dart';
export 'models/billing_invoice_issue_outbox_entry.dart';
export 'models/billing_invoice_issue_outbox_filter.dart';
export 'models/billing_invoice_issue_outbox_health.dart';
export 'models/billing_invoice_issue_outbox_retry_policy.dart';
export 'models/billing_invoice_issue_outbox_retry_snapshot.dart';
export 'models/billing_invoice_issue_outbox_saved_view.dart';
export 'models/billing_invoice_issue_outbox_selection.dart';
export 'models/billing_invoice_issue_outbox_sort.dart';
export 'models/billing_invoice_issue_outbox_sync_summary.dart';
export 'models/billing_invoice_issue_outbox_view_state.dart';
export 'models/billing_invoice_issue_plan.dart';
export 'models/billing_invoice_tax_mode.dart';
export 'models/billing_navigation_destination.dart';
export 'models/billing_navigation_destination_id.dart';
export 'models/billing_payment_schedule.dart';
export 'models/billing_exception_event.dart';
export 'models/billing_policy_capability.dart';
export 'models/billing_policy_config.dart';
export 'models/exception_relief_plan.dart';
export 'models/follow_up_work_action_state.dart';
export 'models/follow_up_work_item.dart';
export 'models/follow_up_work_queue_filter.dart';
export 'models/policy_exception_plan.dart';
export 'models/relief_application_packet.dart';
export 'models/relief_approval_guidance.dart';
export 'models/relief_execution_plan.dart';
export 'models/relief_impact_summary.dart';
export 'models/relief_monitoring_plan.dart';
export 'models/split_allocation_plan.dart';
export 'models/billing_product.dart';
export 'models/billing_product_filter.dart';
export 'models/billing_route_link_navigation_model.dart';
export 'models/billing_tenant.dart';
export 'models/billing_tenant_preferences.dart';
export 'models/domain_pack_contract_action_group.dart';
export 'models/domain_pack_contract_coverage_filter.dart';
export 'models/domain_pack_contract_coverage_sort.dart';
export 'models/domain_pack_contract_coverage_view_state.dart';
export 'models/domain_pack_contract_domain_filter.dart';
export 'repositories/billing_checkout_repository.dart';
export 'repositories/billing_invoice_issue_outbox_repository.dart';
export 'repositories/billing_invoice_issue_outbox_sync_client.dart';
export 'repositories/billing_product_catalog_repository.dart';
export 'repositories/billing_product_tenant_repository.dart';
export 'states/billing_business_domain_blueprint_provider.dart';
export 'states/billing_business_domain_pack_provider.dart';
export 'states/billing_business_domain_profile_provider.dart';
export 'states/billing_cart_provider.dart';
export 'states/billing_checkout_provider.dart';
export 'states/billing_diagnostics_domain_context_provider.dart';
export 'states/billing_diagnostics_overview_provider.dart';
export 'states/billing_diagnostics_release_context_provider.dart';
export 'states/billing_diagnostics_release_profile_filter_provider.dart';
export 'states/billing_diagnostics_release_profile_saved_view_registry_provider.dart';
export 'states/billing_diagnostics_screen_context_provider.dart';
export 'states/billing_diagnostics_section_registry_provider.dart';
export 'states/billing_invoice_issue_outbox_provider.dart';
export 'states/billing_management_navigation_context_provider.dart';
export 'states/billing_product_catalog_provider.dart';
export 'states/billing_product_release_channel_provider.dart';
export 'states/billing_route_contract_provider.dart';
export 'states/billing_route_link_provider.dart';
export 'states/work_center_provider.dart';
export 'utils/billing_business_domain_navigation_policies.dart';
export 'utils/billing_business_domain_pack.dart';
export 'utils/billing_business_domain_pack_readiness.dart';
export 'utils/billing_business_domain_pack_remediation.dart';
export 'utils/billing_business_domain_pack_remediation_navigation.dart';
export 'utils/billing_business_domain_packs.dart';
export 'utils/billing_business_domain_blueprint.dart';
export 'utils/billing_business_domain_blueprint_fit_matrix.dart';
export 'utils/billing_business_domain_blueprint_launch_plan.dart';
export 'utils/billing_business_domain_modules.dart';
export 'utils/billing_business_domain_module_readiness.dart';
export 'utils/billing_business_domain_profiles.dart';
export 'utils/billing_business_domain_screen_registries.dart';
export 'utils/billing_cart_invoice_line_items.dart';
export 'utils/billing_cart_summary.dart';
export 'utils/billing_domain_invoice_draft_composer.dart';
export 'utils/billing_formatters.dart';
export 'utils/billing_diagnostics_route_location.dart';
export 'utils/billing_invoice_draft_composer.dart';
export 'utils/billing_invoice_issue_command.dart';
export 'utils/billing_invoice_issue_policies.dart';
export 'utils/billing_invoice_issue_outbox_health.dart';
export 'utils/billing_invoice_issue_outbox_sync.dart';
export 'utils/billing_invoice_issue_plan.dart';
export 'utils/billing_invoice_line_item_summary.dart';
export 'utils/billing_payment_schedule.dart';
export 'utils/billing_policy_presets.dart';
export 'utils/collection_follow_up_queue.dart';
export 'utils/exception_relief_planner.dart';
export 'utils/follow_up_work_action_registry.dart';
export 'utils/follow_up_work_queue_registry.dart';
export 'utils/policy_exception_planner.dart';
export 'utils/relief_application_packet_builder.dart';
export 'utils/relief_approval_guidance_resolver.dart';
export 'utils/relief_execution_plan_builder.dart';
export 'utils/relief_follow_up_work_items.dart';
export 'utils/relief_impact_analyzer.dart';
export 'utils/relief_monitoring_plan_builder.dart';
export 'utils/split_allocation_planner.dart';
export 'utils/work_center_source_registry.dart';
export 'utils/billing_product_collection.dart';
export 'utils/billing_product_package.dart';
export 'utils/billing_product_package_launch_playbook.dart';
export 'utils/billing_product_package_plan.dart';
export 'utils/billing_product_package_release_bundle.dart';
export 'utils/billing_product_package_release_manifest.dart';
export 'utils/billing_product_release_channel.dart';
export 'utils/billing_product_release_edition.dart';
export 'utils/billing_route_context.dart';
export 'utils/billing_route_contract.dart';
export 'utils/billing_route_contract_remediation.dart';
export 'utils/billing_route_contract_remediation_navigation.dart';
export 'utils/billing_route_definition_registry.dart';
export 'utils/billing_route_execution_contract.dart';
export 'utils/billing_route_extension_manifest.dart';
export 'utils/billing_route_extension_manifest_remediation.dart';
export 'utils/billing_route_page_builder_registry.dart';
export 'utils/billing_route_link.dart';
export 'utils/billing_route_locations.dart';
export 'utils/billing_release_gate.dart';
export 'utils/billing_tenant_context_bridge.dart';
export 'utils/billing_tenant_domain_module.dart';
export 'utils/billing_tenant_domain_profile.dart';
export 'utils/domain_pack_contract.dart';
export 'widgets/billing_cart_bottom_sheet.dart';
export 'widgets/billing_cart_item_tile.dart';
export 'widgets/billing_cart_panel.dart';
export 'widgets/billing_checkout_bar.dart';
export 'widgets/billing_checkout_dialog.dart';
export 'widgets/billing_checkout_receipt_sheet.dart';
export 'widgets/billing_checkout_review.dart';
export 'widgets/billing_empty_state.dart';
export 'widgets/collection_follow_up_queue_panel.dart';
export 'widgets/billing_diagnostics_content.dart';
export 'widgets/billing_diagnostics_release_profile_filter_hydrator.dart';
export 'widgets/billing_diagnostics_screen.dart';
export 'widgets/billing_diagnostics_domain_signal_card.dart';
export 'widgets/billing_diagnostics_domain_section.dart';
export 'widgets/billing_diagnostics_domain_signal_section.dart';
export 'widgets/billing_diagnostics_navigation_coverage_panel.dart';
export 'widgets/billing_diagnostics_navigation_section.dart';
export 'widgets/billing_diagnostics_overview_panel.dart';
export 'widgets/billing_diagnostics_pack_summary_card.dart';
export 'widgets/billing_diagnostics_remediation_summary_card.dart';
export 'widgets/billing_diagnostics_release_summary_card.dart';
export 'widgets/billing_diagnostics_release_section.dart';
export 'widgets/billing_diagnostics_scope_pill.dart';
export 'widgets/billing_diagnostics_section_profile.dart';
export 'widgets/billing_release_gate_lane_target.dart';
export 'widgets/billing_release_gate_panel.dart';
export 'widgets/billing_diagnostics_section_registry.dart';
export 'widgets/billing_route_contract_panel.dart';
export 'widgets/billing_route_contract_remediation_list.dart';
export 'widgets/billing_route_extension_manifest_panel.dart';
export 'widgets/billing_route_extension_manifest_remediation_list.dart';
export 'widgets/billing_route_unavailable_screen.dart';
export 'widgets/diagnostics_link_action.dart';
export 'widgets/diagnostics_release_profile_filter_badge.dart';
export 'widgets/diagnostics_release_profile_saved_view.dart';
export 'widgets/diagnostics_release_profile_saved_view_registry.dart';
export 'widgets/domain_pack_contract_action_strip.dart';
export 'widgets/domain_pack_contract_coverage_filter_bar.dart';
export 'widgets/domain_pack_contract_coverage_panel.dart';
export 'widgets/domain_pack_contract_coverage_scope_summary.dart';
export 'widgets/domain_pack_contract_coverage_sort_menu.dart';
export 'widgets/domain_pack_contract_domain_filter.dart';
export 'widgets/domain_pack_contract_requirement_list.dart';
export 'widgets/domain_pack_contract_summary_card.dart';
export 'widgets/standard_billing_diagnostics_section_profiles.dart';
export 'widgets/billing_business_domain_blueprint_fit_matrix_panel.dart';
export 'widgets/billing_business_domain_blueprint_launch_plan_panel.dart';
export 'widgets/billing_business_domain_blueprint_panel.dart';
export 'widgets/billing_product_package_launch_playbook_metrics.dart';
export 'widgets/billing_product_package_launch_playbook_panel.dart';
export 'widgets/billing_product_package_metric_provider_registry.dart';
export 'widgets/billing_product_package_metrics.dart';
export 'widgets/billing_product_package_panel.dart';
export 'widgets/billing_product_package_panel_registry.dart';
export 'widgets/billing_product_package_release_bundle_metrics.dart';
export 'widgets/billing_product_package_release_bundle_panel.dart';
export 'widgets/billing_product_package_release_manifest_metrics.dart';
export 'widgets/billing_product_package_release_manifest_panel.dart';
export 'widgets/billing_product_release_channel_launch_dispatch_plan.dart';
export 'widgets/billing_product_release_channel_launch_dispatch_presentation.dart';
export 'widgets/billing_product_release_channel_launch_dispatch_status.dart';
export 'widgets/billing_product_release_channel_launch_action_feed.dart';
export 'widgets/billing_product_release_channel_launch_metric_provider_registry.dart';
export 'widgets/billing_product_release_channel_launch_metrics.dart';
export 'widgets/billing_product_release_channel_launch_panel_registry.dart';
export 'widgets/billing_product_release_channel_launch_panel_sources.dart';
export 'widgets/billing_product_release_channel_launch_plan_panel.dart';
export 'widgets/billing_product_release_channel_launch_queue.dart';
export 'widgets/billing_product_release_channel_launch_queue_metrics.dart';
export 'widgets/billing_product_release_channel_launch_queue_panel.dart';
export 'widgets/billing_product_release_channel_launch_runbook.dart';
export 'widgets/billing_product_release_channel_launch_runbook_metrics.dart';
export 'widgets/billing_product_release_channel_launch_runbook_panel.dart';
export 'widgets/billing_readiness_panel_deck.dart';
export 'widgets/billing_readiness_panel_descriptor.dart';
export 'widgets/billing_readiness_metric_provider_panel.dart';
export 'widgets/billing_readiness_metric_provider.dart';
export 'widgets/billing_product_release_channel_matrix_metrics.dart';
export 'widgets/billing_product_release_channel_matrix_panel.dart';
export 'widgets/billing_product_release_edition_metrics.dart';
export 'widgets/billing_product_release_edition_panel.dart';
export 'widgets/billing_product_release_metric_provider_registry.dart';
export 'widgets/billing_product_release_panel_registry.dart';
export 'widgets/billing_readiness_metric_collection.dart';
export 'widgets/billing_domain_module_catalog_model.dart';
export 'widgets/billing_release_workspace_action.dart';
export 'widgets/billing_release_workspace_composition.dart';
export 'widgets/billing_release_workspace_controller.dart';
export 'widgets/billing_release_workspace_domain_focus.dart';
export 'widgets/billing_release_workspace_profile.dart';
export 'widgets/billing_release_workspace_registry.dart';
export 'widgets/billing_release_workspace_saved_view.dart';
export 'widgets/billing_release_workspace_snapshot.dart';
export 'widgets/billing_release_workspace_view.dart';
export 'widgets/standard_release_workspace_profiles.dart';
export 'widgets/billing_domain_module_catalog_panel.dart';
export 'widgets/billing_business_domain_pack_remediation_components.dart';
export 'widgets/billing_business_domain_pack_remediation_panel.dart';
export 'widgets/billing_business_domain_pack_readiness_badge.dart';
export 'widgets/billing_business_domain_pack_readiness_issue_list.dart';
export 'widgets/billing_business_domain_pack_readiness_tile.dart';
export 'widgets/billing_business_domain_pack_registry_readiness_panel.dart';
export 'widgets/billing_domain_module_readiness_frame.dart';
export 'widgets/billing_domain_module_readiness_badge.dart';
export 'widgets/billing_domain_module_readiness_panel.dart';
export 'widgets/billing_domain_module_registry_readiness_panel.dart';
export 'widgets/billing_order_summary.dart';
export 'widgets/billing_invoice_issue_outbox_active_view_banner.dart';
export 'widgets/billing_invoice_issue_outbox_bulk_action_bar.dart';
export 'widgets/billing_invoice_issue_plan_preview.dart';
export 'widgets/billing_invoice_issue_outbox_entry_tile.dart';
export 'widgets/billing_invoice_issue_outbox_filter_bar.dart';
export 'widgets/billing_invoice_issue_outbox_health_panel.dart';
export 'widgets/billing_invoice_issue_outbox_inspector_sheet.dart';
export 'widgets/billing_invoice_issue_outbox_saved_view_bar.dart';
export 'widgets/billing_invoice_issue_outbox_sort_menu.dart';
export 'widgets/billing_invoice_issue_outbox_sync_summary_banner.dart';
export 'widgets/billing_exception_policy_panel.dart';
export 'widgets/exception_relief_plan_panel.dart';
export 'widgets/follow_up_work_queue_filter_bar.dart';
export 'widgets/follow_up_work_queue_panel.dart';
export 'widgets/work_center_screen.dart';
export 'widgets/work_center_panel.dart';
export 'widgets/relief_application_packet_panel.dart';
export 'widgets/relief_approval_guidance_panel.dart';
export 'widgets/relief_execution_plan_panel.dart';
export 'widgets/relief_impact_summary_panel.dart';
export 'widgets/relief_monitoring_plan_panel.dart';
export 'widgets/billing_domain_navigation_policy.dart';
export 'widgets/billing_management_initial_local_navigation_controller.dart';
export 'widgets/billing_management_local_target_action_set.dart';
export 'widgets/billing_management_local_target_controller.dart';
export 'widgets/billing_management_navigation_action_controller.dart';
export 'widgets/billing_management_navigation_coordinator.dart';
export 'widgets/billing_management_navigation_session.dart';
export 'widgets/billing_management_navigation_scaffold.dart';
export 'widgets/billing_management_quick_action_menu.dart';
export 'widgets/billing_management_route_fallback_controller.dart';
export 'widgets/billing_management_route_local_fallback_controller.dart';
export 'widgets/billing_management_route_open_controller.dart';
export 'widgets/billing_management_surface_route_fallback_controller.dart';
export 'widgets/billing_navigation_action_resolver.dart';
export 'widgets/billing_app_route_navigator.dart';
export 'widgets/billing_navigation_coverage_badge.dart';
export 'widgets/billing_navigation_coverage.dart';
export 'widgets/billing_product_card.dart';
export 'widgets/billing_product_catalog_toolbar.dart';
export 'widgets/billing_product_category_filter.dart';
export 'widgets/billing_product_category_icon.dart';
export 'widgets/billing_product_grid.dart';
export 'widgets/billing_product_workspace_screen.dart';
export 'widgets/billing_navigation_drawer.dart';
export 'widgets/billing_navigation_dispatch_plan.dart';
export 'widgets/billing_navigation_dispatch_snapshot.dart';
export 'widgets/billing_navigation_dispatch_summary.dart';
export 'widgets/billing_navigation_launch_center.dart';
export 'widgets/billing_navigation_launch_planner.dart';
export 'widgets/billing_navigation_launch_snapshot.dart';
export 'widgets/billing_navigation_launch_state.dart';
export 'widgets/billing_navigation_local_target.dart';
export 'widgets/billing_navigation_route_intent.dart';
export 'widgets/billing_navigation_route_target.dart';
export 'widgets/billing_navigation_scaffold.dart';
export 'widgets/billing_policy_capability_matrix.dart';
export 'widgets/billing_policy_center_content.dart';
export 'widgets/billing_policy_center_screen.dart';
export 'widgets/policy_exception_decision_panel.dart';
export 'widgets/split_allocation_preview_panel.dart';
export 'widgets/billing_quick_action_menu.dart';
export 'widgets/billing_route_context_hydrator.dart';
export 'widgets/billing_tenant_avatar.dart';
export 'widgets/billing_tenant_selection_screen.dart';

class BillingApp extends StatelessWidget {
  const BillingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Multi-Tenant Billing',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: 'Inter',
          scaffoldBackgroundColor: const Color(0xFFF8F9FC),
          appBarTheme: const AppBarTheme(
            backgroundColor: Colors.white,
            elevation: 0,
            iconTheme: IconThemeData(color: Color(0xFF4A5568)),
            titleTextStyle: TextStyle(
              color: Color(0xFF2D3748),
              fontSize: 18,
              fontWeight: FontWeight.w600,
            ),
          ),
          cardTheme: CardThemeData(
            elevation: 0,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(14),
            ),
          ),
        ),
        home: const BillingScreen(),
      ),
    );
  }
}

void main() {
  runApp(const BillingApp());
}
