import 'package:ky_restaurant/ky_restaurant.dart';

const restaurantTestFloorZones = [
  RestaurantServiceZone(
    id: 'main-floor',
    name: 'Main Floor',
    section: 'Dining',
    occupiedTables: 18,
    totalTables: 22,
    covers: 72,
    waitList: 6,
    ticketMinutes: 17,
    status: RestaurantServiceStatus.busy,
  ),
  RestaurantServiceZone(
    id: 'terrace',
    name: 'Terrace',
    section: 'Outdoor',
    occupiedTables: 9,
    totalTables: 14,
    covers: 34,
    waitList: 2,
    ticketMinutes: 14,
    status: RestaurantServiceStatus.calm,
  ),
  RestaurantServiceZone(
    id: 'private-room',
    name: 'Private Room',
    section: 'Events',
    occupiedTables: 4,
    totalTables: 4,
    covers: 28,
    waitList: 0,
    ticketMinutes: 22,
    status: RestaurantServiceStatus.critical,
  ),
];

const restaurantTestKitchenStations = [
  RestaurantKitchenStation(
    id: 'grill',
    name: 'Grill',
    lead: 'Ari',
    ticketsInProgress: 12,
    averageFireMinutes: 21,
    queueLabel: 'Steaks',
    status: RestaurantServiceStatus.critical,
  ),
  RestaurantKitchenStation(
    id: 'wok',
    name: 'Wok',
    lead: 'Mei',
    ticketsInProgress: 8,
    averageFireMinutes: 15,
    queueLabel: 'Noodles',
    status: RestaurantServiceStatus.busy,
  ),
  RestaurantKitchenStation(
    id: 'cold',
    name: 'Cold Pass',
    lead: 'Dimas',
    ticketsInProgress: 5,
    averageFireMinutes: 8,
    queueLabel: 'Salads',
    status: RestaurantServiceStatus.calm,
  ),
];

const restaurantTestShiftTasks = [
  RestaurantShiftTask(
    id: 'open',
    title: 'Reset patio section',
    owner: 'Floor team',
    dueLabel: 'Due in 12m',
    progress: .45,
    status: RestaurantServiceStatus.calm,
  ),
  RestaurantShiftTask(
    id: 'attention',
    title: 'Restock dessert station',
    owner: 'Pastry',
    dueLabel: 'Due now',
    progress: .2,
    status: RestaurantServiceStatus.critical,
  ),
  RestaurantShiftTask(
    id: 'done',
    title: 'Confirm VIP setup',
    owner: 'Host',
    dueLabel: 'Done',
    progress: 1,
    status: RestaurantServiceStatus.calm,
  ),
];

const restaurantTestMenuSignals = [
  RestaurantMenuSignal(
    id: 'risk',
    name: 'Short Rib Rendang',
    category: 'Main',
    orders: 32,
    grossMarginPercent: 71,
    soldOutRiskPercent: 78,
    prepMinutes: 18,
    tags: ['Low stock'],
  ),
  RestaurantMenuSignal(
    id: 'quick',
    name: 'Pandan Spritz',
    category: 'Beverage',
    orders: 24,
    grossMarginPercent: 68,
    soldOutRiskPercent: 18,
    prepMinutes: 5,
    tags: ['Fast'],
  ),
  RestaurantMenuSignal(
    id: 'dessert',
    name: 'Burnt Cheesecake',
    category: 'Dessert',
    orders: 18,
    grossMarginPercent: 62,
    soldOutRiskPercent: 12,
    prepMinutes: 7,
    tags: ['Restocked'],
  ),
];

const restaurantTestQuickMenuSignals = [
  RestaurantMenuSignal(
    id: 'quick',
    name: 'Pandan Spritz',
    category: 'Beverage',
    orders: 24,
    grossMarginPercent: 68,
    soldOutRiskPercent: 18,
    prepMinutes: 5,
    tags: ['Fast'],
  ),
];

const restaurantTestReservations = [
  RestaurantReservation(
    id: 'late',
    guestName: 'Wijaya Family',
    partySize: 8,
    timeLabel: '19:05',
    arrivalMinutesFromNow: -8,
    zoneLabel: 'Terrace',
    tableLabel: 'Table 21',
    phoneNumber: '+62 812 3456 7002',
    status: RestaurantReservationStatus.late,
    source: RestaurantReservationSource.phone,
    notes: 'Needs stroller space.',
  ),
  RestaurantReservation(
    id: 'vip',
    guestName: 'Sari Putri',
    partySize: 6,
    timeLabel: '19:15',
    arrivalMinutesFromNow: 12,
    zoneLabel: 'Main Floor',
    tableLabel: 'Table 12',
    phoneNumber: '+62 812 3456 7001',
    emailAddress: 'sari.putri@example.test',
    status: RestaurantReservationStatus.confirmed,
    source: RestaurantReservationSource.online,
    isVip: true,
  ),
  RestaurantReservation(
    id: 'arrived',
    guestName: 'Andini',
    partySize: 2,
    timeLabel: '19:20',
    arrivalMinutesFromNow: 18,
    zoneLabel: 'Bar Counter',
    status: RestaurantReservationStatus.arrived,
    source: RestaurantReservationSource.walkIn,
  ),
  RestaurantReservation(
    id: 'closed',
    guestName: 'Cancelled Guest',
    partySize: 4,
    timeLabel: '18:30',
    arrivalMinutesFromNow: -40,
    zoneLabel: 'Main Floor',
    status: RestaurantReservationStatus.cancelled,
    source: RestaurantReservationSource.concierge,
  ),
];
