import 'package:flutter/material.dart';

import 'models/class_group.dart';
import 'models/enums.dart';
import 'models/hafidz_progress.dart';
import 'models/student.dart';
import 'models/subject.dart';
import 'models/surah.dart';
import 'models/teacher.dart';

final studentsDummy = [
  Student(
    id: 1,
    name: 'Alice Johnson',
    profileImage: 'assets/profile1.png',
    rollNumber: 'A001',
  ),
  Student(
    id: 2,
    name: 'Bob Smith',
    profileImage: 'assets/profile2.png',
    rollNumber: 'A002',
  ),
  Student(
    id: 3,
    name: 'Charlie Brown',
    profileImage: 'assets/profile3.png',
    rollNumber: 'A003',
  ),
  Student(
    id: 4,
    name: 'David Miller',
    profileImage: 'assets/profile4.png',
    rollNumber: 'A004',
  ),
  Student(
    id: 5,
    name: 'Emma Wilson',
    profileImage: 'assets/profile5.png',
    rollNumber: 'A005',
  ),
  Student(
    id: 6,
    name: 'Frank Thomas',
    profileImage: 'assets/profile6.png',
    rollNumber: 'B001',
  ),
  Student(
    id: 7,
    name: 'Grace Lee',
    profileImage: 'assets/profile7.png',
    rollNumber: 'B002',
  ),
  Student(
    id: 8,
    name: 'Henry Zhang',
    profileImage: 'assets/profile8.png',
    rollNumber: 'B003',
  ),
  Student(
    id: 9,
    name: 'Emma Wilson',
    email: 'emma.w@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/women/17.jpg',
    enrolledSubjects: ['1', '3'],
  ),
  Student(
    id: 10,
    name: 'David Lee',
    email: 'david.l@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/men/91.jpg',
    enrolledSubjects: ['1', '2'],
  ),
  Student(
    id: 11,
    name: 'Olivia Martinez',
    email: 'olivia.m@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/women/62.jpg',
    enrolledSubjects: ['1', '2'],
  ),
  Student(
    id: 12,
    name: 'Ethan Johnson',
    email: 'ethan.j@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/men/55.jpg',
    enrolledSubjects: ['1', '3'],
  ),
  Student(
    id: 13,
    name: 'Sophia Wang',
    email: 'sophia.w@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/women/28.jpg',
    enrolledSubjects: ['1', '3'],
  ),
  Student(
    id: 14,
    name: 'Noah Garcia',
    email: 'noah.g@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/men/75.jpg',
    enrolledSubjects: ['2'],
  ),
  Student(
    id: 15,
    name: 'Ava Thompson',
    email: 'ava.t@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/women/35.jpg',
    enrolledSubjects: ['2'],
  ),
  Student(
    id: 16,
    name: 'Liam Brown',
    email: 'liam.b@example.edu',
    profileImage: 'https://randomuser.me/api/portraits/men/24.jpg',
    enrolledSubjects: ['3'],
  ),
];

final List<ClassGroup> classGroupsDummy = [
  ClassGroup(
    id: 1,
    name: 'Class A',
    subjectId: 1,
    studentIds: [1, 2, 3, 4, 5],
    schedule: 'Mon, Wed, Fri - 10:00 AM',
    startDate: DateTime(2025, 1, 15),
    endDate: DateTime(2025, 5, 30),
  ),
  ClassGroup(
    id: 2,
    name: 'Class B',
    subjectId: 2,
    studentIds: [6, 7, 8],
    schedule: 'Mon, Wed, Fri - 10:00 AM',
    startDate: DateTime(2025, 1, 15),
    endDate: DateTime(2025, 5, 30),
  ),
  ClassGroup(
    id: 1,
    name: 'Physics 101',
    teacherId: '1',
    studentIds: [1, 2, 4],
    subjectId: 1,
    schedule: 'Mon, Wed, Fri - 10:00 AM',
    startDate: DateTime(2025, 1, 15),
    endDate: DateTime(2025, 5, 30),
  ),
  ClassGroup(
    id: 2,
    name: 'Advanced Mathematics',
    teacherId: '2',
    studentIds: [3, 4, 5, 7],
    subjectId: 2,
    schedule: 'Tue, Thu - 2:00 PM',
    startDate: DateTime(2025, 1, 16),
    endDate: DateTime(2025, 5, 25),
  ),
  ClassGroup(
    id: 3,
    name: 'Computer Science 202',
    teacherId: '3',
    studentIds: [3, 4, 5, 6],
    subjectId: 3,
    schedule: 'Mon, Wed - 3:30 PM',
    startDate: DateTime(2025, 1, 14),
    endDate: DateTime(2025, 5, 27),
  ),
];

final List<Teacher> teachersDummy = [
  // Sample data
  Teacher(
    id: 1,
    employeeId: "TCH00123",
    firstName: "Ahmed",
    lastName: "Khalid",
    dateOfBirth: DateTime(1985, 3, 15),
    hireDate: DateTime(2018, 9, 1),
    phoneNumber: "+6012345678",
    email: "ahmed.khalid@school.edu",
    address: "123 Jalan Ampang, Kuala Lumpur",
    qualification: "Ph.D in Islamic Studies",
    expertise: "Tafsir, Hadith Studies",
    gender: Gender.male,
    employmentType: EmploymentType.fullTime,
  ),
  Teacher(
    id: 2,
    employeeId: "TCH00124",
    firstName: "Fatimah",
    lastName: "Abdullah",
    dateOfBirth: DateTime(1990, 6, 22),
    hireDate: DateTime(2019, 1, 15),
    phoneNumber: "+6013456789",
    email: "fatimah.a@school.edu",
    qualification: "Master's in Arabic Literature",
    expertise: "Classical Arabic, Poetry",
    gender: Gender.female,
    employmentType: EmploymentType.fullTime,
  ),
  Teacher(
    id: 3,
    employeeId: "TCH00125",
    firstName: "Yusuf",
    lastName: "Ibrahim",
    dateOfBirth: DateTime(1978, 11, 8),
    hireDate: DateTime(2015, 7, 10),
    phoneNumber: "+6014567890",
    qualification: "Bachelor's in Education",
    expertise: "Quranic Memorization",
    isActive: false,
    gender: Gender.male,
    employmentType: EmploymentType.partTime,
  ),
  Teacher(
    id: 1,
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@example.edu',
    photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    subjectsIds: [1, 2],
  ),
  Teacher(
    id: 2,
    name: 'Prof. James Smith',
    email: 'james.smith@example.edu',
    photoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    subjectsIds: [2],
  ),
  Teacher(
    id: 3,
    name: 'Dr. Michael Chen',
    email: 'michael.chen@example.edu',
    photoUrl: 'https://randomuser.me/api/portraits/men/22.jpg',
    subjectsIds: [3],
  ),
];

final List<Subject> subjectDummy = [
  Subject(
    id: 1,
    name: 'Physics',
    code: 'PHY101',
    color: Color(0xFF5C6BC0),
    subjectType: SubjectType.academic,
    difficultyLevel: DifficultyLevel.beginner,
  ),
  Subject(
    id: 2,
    name: 'Mathematics',
    code: 'MTH202',
    color: Color(0xFF66BB6A),
    subjectType: SubjectType.academic,
    difficultyLevel: DifficultyLevel.beginner,
  ),
  Subject(
    id: 3,
    name: 'Computer Science',
    code: 'CS202',
    color: Color(0xFFEF5350),
    subjectType: SubjectType.academic,
    difficultyLevel: DifficultyLevel.beginner,
  ),
];

final List<Surah> surahDummy = [
  Surah(
    id: 1,
    number: 1,
    name: "الفاتحة",
    transliteration: "Al-Fatihah",
    translation: "The Opening",
    totalVerses: 7,
    type: "Meccan",
  ),
  Surah(
    id: 2,
    number: 2,
    name: "البقرة",
    transliteration: "Al-Baqarah",
    translation: "The Cow",
    totalVerses: 286,
    type: "Medinan",
  ),
  Surah(
    id: 3,
    number: 3,
    name: "آل عمران",
    transliteration: "Ali 'Imran",
    translation: "Family of Imran",
    totalVerses: 200,
    type: "Medinan",
  ),
  Surah(
    id: 4,
    number: 4,
    name: "النساء",
    transliteration: "An-Nisa",
    translation: "The Women",
    totalVerses: 176,
    type: "Medinan",
  ),
  Surah(
    id: 5,
    number: 5,
    name: "المائدة",
    transliteration: "Al-Ma'idah",
    translation: "The Table Spread",
    totalVerses: 120,
    type: "Medinan",
  ),
  Surah(
    id: 36,
    number: 36,
    name: "يس",
    transliteration: "Ya-Sin",
    translation: "Ya Sin",
    totalVerses: 83,
    type: "Meccan",
  ),
  Surah(
    id: 112,
    number: 112,
    name: "الإخلاص",
    transliteration: "Al-Ikhlas",
    translation: "Sincerity",
    totalVerses: 4,
    type: "Meccan",
  ),
  Surah(
    id: 113,
    number: 113,
    name: "الفلق",
    transliteration: "Al-Falaq",
    translation: "The Daybreak",
    totalVerses: 5,
    type: "Meccan",
  ),
  Surah(
    id: 114,
    number: 114,
    name: "الناس",
    transliteration: "An-Nas",
    translation: "Mankind",
    totalVerses: 6,
    type: "Meccan",
  ),
];

final List<HafizProgress> hafizProgressDummy = [
  HafizProgress(
    id: 1,
    date: DateTime.now().subtract(const Duration(days: 1)),
    startVerse: 1,
    endVerse: 7,
    comments: "Excellent tajweed application, good fluency.",
    qualityScore: 9.0,
    memorizationStatus: MemorizationStatus.completed,
    student: Student(id: 1, name: 'name'),
    surahId: 1, // Al-Fatihah
    assessor: Teacher(id: 2),
  ),
  HafizProgress(
    id: 2,
    date: DateTime.now().subtract(const Duration(days: 3)),
    startVerse: 1,
    endVerse: 5,
    comments: "Good pronunciation, but needs to work on fluency.",
    qualityScore: 7.5,
    memorizationStatus: MemorizationStatus.inProgress,
    student: Student(id: 1, name: 'name'),
    surahId: 112, // Al-Ikhlas
    assessor: Teacher(id: 2),
  ),
  HafizProgress(
    id: 3,
    date: DateTime.now().subtract(const Duration(days: 5)),
    startVerse: 1,
    endVerse: 5,
    comments: "Struggled with pronunciation of certain words.",
    qualityScore: 6.0,
    memorizationStatus: MemorizationStatus.needsRevision,
    student: Student(id: 1, name: 'name'),
    surahId: 113, //113), // Al-Falaq
    assessor: Teacher(id: 2),
  ),
  HafizProgress(
    id: 4,
    date: DateTime.now().subtract(const Duration(days: 7)),
    startVerse: 1,
    endVerse: 6,
    comments: "Excellent work. All verses memorized perfectly.",
    qualityScore: 9.5,
    memorizationStatus: MemorizationStatus.mastered,
    student: Student(id: 1, name: 'name'),
    surahId: 114, // An-Nas
    assessor: Teacher(id: 2),
  ),
  HafizProgress(
    id: 5,
    date: DateTime.now().subtract(const Duration(days: 14)),
    startVerse: 1,
    endVerse: 10,
    comments: "Good start on this surah, making progress.",
    qualityScore: 7.0,
    memorizationStatus: MemorizationStatus.inProgress,
    student: Student(id: 1, name: 'name'),
    surahId: 2, // Al-Baqarah
    assessor: Teacher(id: 2),
  ),
  HafizProgress(
    id: 6,
    date: DateTime.now().subtract(const Duration(days: 16)),
    startVerse: 11,
    endVerse: 20,
    comments: "Continued progress, but needs to work on verse 15-17.",
    qualityScore: 6.5,
    memorizationStatus: MemorizationStatus.needsRevision,
    student: Student(id: 1, name: 'name'),
    surahId: 2, // Al-Baqarah
    assessor: Teacher(id: 2),
  ),
  HafizProgress(
    id: 7,
    date: DateTime.now().subtract(const Duration(days: 45)),
    startVerse: 1,
    endVerse: 10,
    comments: "Started memorization of Ya-Sin with good tajweed.",
    qualityScore: 8.0,
    memorizationStatus: MemorizationStatus.inProgress,
    student: Student(id: 1, name: 'name'),
    surahId: 36, // Ya-Sin
    assessor: Teacher(id: 2),
  ),
];

final materialsDummy = [
  {
    'title': 'Lecture Notes',
    'type': 'PDF',
    'date': '2023-10-01',
    'icon': Icons.picture_as_pdf,
  },
  {
    'title': 'Assignment 1',
    'type': 'DOCX',
    'date': '2023-10-05',
    'icon': Icons.description,
  },
  {
    'title': 'Project Guidelines',
    'type': 'PPTX',
    'date': '2023-10-10',
    'icon': Icons.slideshow,
  },
  {
    'title': 'Course Syllabus',
    'type': 'PDF',
    'date': 'Jan 15, 2025',
    'icon': Icons.description,
  },
  {
    'title': 'Lecture Notes - Week 1',
    'type': 'PDF',
    'date': 'Jan 18, 2025',
    'icon': Icons.note,
  },
  {
    'title': 'Assignment 1',
    'type': 'DOCX',
    'date': 'Jan 22, 2025',
    'icon': Icons.assignment,
  },
  {
    'title': 'Lab Instructions',
    'type': 'PDF',
    'date': 'Jan 25, 2025',
    'icon': Icons.science,
  },
];
