#mp.messaging.incoming.words-in.auto.offset.reset=earliest
#mp.messaging.incoming.words-in.topic=words
#mp.messaging.outgoing.words-out.topic=words

# Kafka configuration
kafka.bootstrap.servers=localhost:9092

# Producer configuration
mp.messaging.outgoing.messages-out.connector=smallrye-kafka
mp.messaging.outgoing.messages-out.topic=messages
mp.messaging.outgoing.messages-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer configuration
mp.messaging.incoming.messages-in.connector=smallrye-kafka
mp.messaging.incoming.messages-in.topic=messages
mp.messaging.incoming.messages-in.group.id=kafka-manager-group
mp.messaging.incoming.messages-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.auto.offset.reset=earliest

# Kafka Streams configuration
quarkus.kafka-streams.application-id=kafka-manager-streams
quarkus.kafka-streams.bootstrap-servers=${kafka.bootstrap.servers}

# REST API docs
quarkus.swagger-ui.enable=true
quarkus.smallrye-openapi.path=/openapi