import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:queue_ui/camel/models/node_connection.dart';

import '../models/node_card.dart';
import '../models/node.dart';
import '../models/route_template.dart';

final templatesProvider = Provider<List<RouteTemplate>>((ref) {
  return [
    RouteTemplate(
      id: 'kafka-to-db',
      name: 'Kafka to Database',
      description:
          'Stream data from Kafka topic to database with transformation',
      category: 'Data Integration',
      icon: Icons.storage,
      route: WNode(
        id: 'template-1',
        name: 'Kafka to Database',
        description: 'Consumes messages from Kafka and inserts into database',
        nodes: [
          NodeCard(
            id: '1',
            type: 'kafka',
            name: 'Kafka',
            icon: Icons.bolt,
            color: Colors.purple,
            position: const Offset(100, 200),
            config: {
              'topic': 'input-topic',
              'brokers': 'localhost:9092',
              'groupId': 'db-consumer',
            },
          ),
          NodeCard(
            id: '2',
            type: 'unmarshal',
            name: 'Unmarshal',
            icon: Icons.unarchive,
            color: Colors.teal,
            position: const Offset(300, 200),
            config: {'format': 'json'},
            connections: [NodeConnection(targetNodeId: '3')],
          ),
          NodeCard(
            id: '3',
            type: 'log',
            name: 'Log',
            icon: Icons.article,
            color: Colors.grey,
            position: const Offset(500, 200),
            config: {'message': 'Processing: \${body}', 'level': 'INFO'},
            connections: [NodeConnection(targetNodeId: '4')],
          ),
          NodeCard(
            id: '4',
            type: 'database-out',
            name: 'Database',
            icon: Icons.storage,
            color: Colors.indigo,
            position: const Offset(700, 200),
            config: {
              'query':
                  'INSERT INTO messages (id, data) VALUES (:\${body.id}, :\${body})',
              'dataSource': 'default',
            },
          ),
        ],
      ),
      tags: ['kafka', 'database', 'streaming', 'etl'],
      usageCount: 1250,
      rating: 4.8,
      author: 'Apache Camel Team',
    ),
    RouteTemplate(
      id: 'rest-api-gateway',
      name: 'REST API Gateway',
      description:
          'API Gateway with routing, transformation and error handling',
      category: 'API',
      icon: Icons.api,
      route: WNode(
        id: 'template-2',
        name: 'REST API Gateway',
        description: 'RESTful API gateway with content-based routing',
        nodes: [
          NodeCard(
            id: '1',
            type: 'rest',
            name: 'REST API',
            icon: Icons.api,
            color: Colors.blue,
            position: const Offset(100, 200),
            config: {'path': '/api/users', 'method': 'POST'},
          ),
          NodeCard(
            id: '2',
            type: 'unmarshal',
            name: 'Unmarshal',
            icon: Icons.unarchive,
            color: Colors.teal,
            position: const Offset(300, 200),
            config: {'format': 'json'},
            connections: [NodeConnection(targetNodeId: '3')],
          ),
          NodeCard(
            id: '3',
            type: 'choice',
            name: 'Choice',
            icon: Icons.call_split,
            color: Colors.pink,
            position: const Offset(500, 200),
            config: {'conditions': []},
            connections: [
              NodeConnection(targetNodeId: '4'),
              NodeConnection(targetNodeId: '5'),
            ],
          ),
          NodeCard(
            id: '4',
            type: 'rest-out',
            name: 'Backend A',
            icon: Icons.api,
            color: Colors.blue,
            position: const Offset(700, 150),
            config: {'uri': 'http://backend-a:8080/process', 'method': 'POST'},
          ),
          NodeCard(
            id: '5',
            type: 'rest-out',
            name: 'Backend B',
            icon: Icons.api,
            color: Colors.blue,
            position: const Offset(700, 250),
            config: {'uri': 'http://backend-b:8080/process', 'method': 'POST'},
          ),
        ],
      ),
      tags: ['rest', 'api', 'gateway', 'routing'],
      usageCount: 890,
      rating: 4.6,
      author: 'Apache Camel Team',
    ),
    RouteTemplate(
      id: 'file-processor',
      name: 'File Processing Pipeline',
      description: 'Poll directory, process files, and archive',
      category: 'File',
      icon: Icons.folder,
      route: WNode(
        id: 'template-3',
        name: 'File Processing',
        description: 'Automated file processing with archival',
        nodes: [
          NodeCard(
            id: '1',
            type: 'file',
            name: 'File',
            icon: Icons.folder,
            color: Colors.green,
            position: const Offset(100, 200),
            config: {'directory': '/input', 'delay': 5000},
          ),
          NodeCard(
            id: '2',
            type: 'log',
            name: 'Log',
            icon: Icons.article,
            color: Colors.grey,
            position: const Offset(300, 200),
            config: {
              'message': 'Processing file: \${header.CamelFileName}',
              'level': 'INFO',
            },
            connections: [NodeConnection(targetNodeId: '3')],
          ),
          NodeCard(
            id: '3',
            type: 'transform',
            name: 'Transform',
            icon: Icons.transform,
            color: Colors.cyan,
            position: const Offset(500, 200),
            config: {'expression': '\${body.toUpperCase()}'},
            connections: [NodeConnection(targetNodeId: '4')],
          ),
          NodeCard(
            id: '4',
            type: 'file-out',
            name: 'File Out',
            icon: Icons.folder,
            color: Colors.green,
            position: const Offset(700, 200),
            config: {
              'directory': '/output',
              'fileName': '\${header.CamelFileName}',
            },
          ),
        ],
      ),
      tags: ['file', 'batch', 'processing'],
      usageCount: 670,
      rating: 4.5,
      author: 'Apache Camel Team',
    ),
    RouteTemplate(
      id: 'event-driven',
      name: 'Event-Driven Architecture',
      description: 'Event sourcing with Kafka and state management',
      category: 'Architecture',
      icon: Icons.architecture,
      route: WNode(
        id: 'template-4',
        name: 'Event-Driven',
        description: 'Event sourcing pattern implementation',
        nodes: [
          NodeCard(
            id: '1',
            type: 'kafka',
            name: 'Events',
            icon: Icons.bolt,
            color: Colors.purple,
            position: const Offset(100, 200),
            config: {
              'topic': 'events',
              'brokers': 'localhost:9092',
              'groupId': 'event-processor',
            },
          ),
          NodeCard(
            id: '2',
            type: 'unmarshal',
            name: 'Unmarshal',
            icon: Icons.unarchive,
            color: Colors.teal,
            position: const Offset(300, 200),
            config: {'format': 'json'},
            connections: [NodeConnection(targetNodeId: '3')],
          ),
          NodeCard(
            id: '3',
            type: 'filter',
            name: 'Filter',
            icon: Icons.filter_alt,
            color: Colors.amber,
            position: const Offset(500, 200),
            config: {'expression': '\${body.eventType} == "ORDER_CREATED"'},
            connections: [NodeConnection(targetNodeId: '4')],
          ),
          NodeCard(
            id: '4',
            type: 'aggregate',
            name: 'Aggregate',
            icon: Icons.merge,
            color: Colors.red,
            position: const Offset(700, 200),
            config: {'correlation': '\${body.userId}', 'completionSize': 10},
            connections: [NodeConnection(targetNodeId: '5')],
          ),
          NodeCard(
            id: '5',
            type: 'kafka-out',
            name: 'Aggregated Events',
            icon: Icons.bolt,
            color: Colors.purple,
            position: const Offset(900, 200),
            config: {'topic': 'aggregated-events', 'brokers': 'localhost:9092'},
          ),
        ],
      ),
      tags: ['event-driven', 'kafka', 'architecture', 'cqrs'],
      usageCount: 450,
      rating: 4.9,
      author: 'Apache Camel Team',
    ),
    RouteTemplate(
      id: 'microservices',
      name: 'Microservices Integration',
      description: 'Inter-service communication with circuit breaker',
      category: 'Microservices',
      icon: Icons.hub,
      route: WNode(
        id: 'template-5',
        name: 'Microservices',
        description: 'Resilient microservices communication',
        nodes: [
          NodeCard(
            id: '1',
            type: 'rest',
            name: 'REST API',
            icon: Icons.api,
            color: Colors.blue,
            position: const Offset(100, 200),
            config: {'path': '/api/orders', 'method': 'POST'},
          ),
          NodeCard(
            id: '2',
            type: 'log',
            name: 'Log Request',
            icon: Icons.article,
            color: Colors.grey,
            position: const Offset(300, 200),
            config: {'message': 'Request: \${body}', 'level': 'INFO'},
            connections: [NodeConnection(targetNodeId: '3')],
          ),
          NodeCard(
            id: '3',
            type: 'throttle',
            name: 'Rate Limit',
            icon: Icons.speed,
            color: Colors.brown,
            position: const Offset(500, 200),
            config: {'maximumRequests': 100, 'timePeriod': 1000},
            connections: [NodeConnection(targetNodeId: '4')],
          ),
          NodeCard(
            id: '4',
            type: 'rest-out',
            name: 'Order Service',
            icon: Icons.api,
            color: Colors.blue,
            position: const Offset(700, 200),
            config: {
              'uri': 'http://order-service:8080/create',
              'method': 'POST',
            },
          ),
        ],
      ),
      tags: ['microservices', 'rest', 'resilience', 'circuit-breaker'],
      usageCount: 780,
      rating: 4.7,
      author: 'Apache Camel Team',
    ),
  ];
});
