import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widget_previews.dart';
import 'package:kaysir/widgets/ui/app_copy_brief_card.dart';
import 'package:kaysir/widgets/ui/app_info_row.dart';
import 'package:kaysir/widgets/ui/app_metric_grid.dart';
import 'package:kaysir/widgets/ui/app_status_pill.dart';

import '../data/project_portfolio_repository.dart';
import '../services/project_decision_brief_pack_service.dart';
import '../services/project_decisions_workspace_service.dart';

/// Copy-ready sponsor/team decision brief pack for project governance reviews.
class ProjectDecisionBriefPackPanel extends StatefulWidget {
  const ProjectDecisionBriefPackPanel({required this.summary, super.key});

  final ProjectDecisionBriefPackSummary summary;

  @override
  State<ProjectDecisionBriefPackPanel> createState() =>
      _ProjectDecisionBriefPackPanelState();
}

/// Keeps copy state local while the brief content is generated by services.
class _ProjectDecisionBriefPackPanelState
    extends State<ProjectDecisionBriefPackPanel> {
  var _briefCopied = false;

  @override
  Widget build(BuildContext context) {
    final summary = widget.summary;
    final colorScheme = Theme.of(context).colorScheme;
    final signalColor = summary.signal.color(colorScheme);
    final briefText = summary.briefText.trim();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        AppInfoRow(
          title: summary.title,
          subtitle: summary.subtitle,
          icon: summary.signal.icon,
          iconStyle: AppInfoRowIconStyle.badge,
          contained: true,
          iconBackgroundColor: signalColor.withValues(alpha: 0.12),
          iconForegroundColor: signalColor,
          titleMaxLines: 2,
          subtitleMaxLines: 2,
          trailing: AppStatusPill(
            label: summary.signal.label,
            icon: summary.signal.icon,
            color: signalColor,
            maxWidth: 124,
          ),
        ),
        const SizedBox(height: 12),
        AppMetricGrid(
          minTileWidth: 128,
          maxColumns: 4,
          metrics: [
            AppMetricGridItem(
              title: 'Highlights',
              value: summary.highlightCount.toString(),
              icon: Icons.auto_awesome_outlined,
              accentColor: colorScheme.primary,
              helper: 'Decision context',
            ),
            AppMetricGridItem(
              title: 'Actions',
              value: summary.actionCount.toString(),
              icon: Icons.pending_actions_outlined,
              accentColor:
                  summary.actionCount == 0
                      ? Colors.green.shade700
                      : Colors.orange.shade700,
              helper: 'Owner steps',
            ),
            AppMetricGridItem(
              title: 'Evidence',
              value: summary.evidenceCount.toString(),
              icon: Icons.fact_check_outlined,
              accentColor: colorScheme.primary,
              helper: 'Proof points',
            ),
            AppMetricGridItem(
              title: 'Route',
              value: summary.signal.label,
              icon: Icons.account_tree_outlined,
              accentColor: signalColor,
              helper: 'Governance signal',
            ),
          ],
        ),
        const SizedBox(height: 12),
        AppInfoRow(
          title: 'Primary decision',
          subtitle: summary.primaryDecisionLabel,
          icon: Icons.rule_folder_outlined,
          iconStyle: AppInfoRowIconStyle.badge,
          contained: true,
          iconBackgroundColor: colorScheme.primary.withValues(alpha: 0.1),
          iconForegroundColor: colorScheme.primary,
          titleMaxLines: 1,
          subtitleMaxLines: 2,
        ),
        const SizedBox(height: 10),
        AppInfoRow(
          title: 'Owner focus',
          subtitle: summary.ownerFocusLabel,
          icon: Icons.groups_outlined,
          iconStyle: AppInfoRowIconStyle.badge,
          contained: true,
          iconBackgroundColor: Colors.orange.shade700.withValues(alpha: 0.1),
          iconForegroundColor: Colors.orange.shade700,
          titleMaxLines: 1,
          subtitleMaxLines: 2,
        ),
        const SizedBox(height: 10),
        AppInfoRow(
          title: 'Governance route',
          subtitle: summary.routeLabel,
          icon: Icons.account_tree_outlined,
          iconStyle: AppInfoRowIconStyle.badge,
          contained: true,
          iconBackgroundColor: signalColor.withValues(alpha: 0.1),
          iconForegroundColor: signalColor,
          titleMaxLines: 1,
          subtitleMaxLines: 2,
        ),
        if (briefText.isNotEmpty) ...[
          const SizedBox(height: 12),
          AppCopyBriefCard(
            title: 'Decision brief pack',
            text: briefText,
            icon: Icons.assignment_turned_in_outlined,
            copied: _briefCopied,
            onCopy: () => _copyBrief(briefText),
          ),
        ],
      ],
    );
  }

  Future<void> _copyBrief(String briefText) async {
    setState(() => _briefCopied = true);
    await Clipboard.setData(ClipboardData(text: briefText));
    if (!mounted) return;

    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text('Decision brief pack copied')));
  }
}

@Preview(name: 'Project decision brief pack panel')
Widget projectDecisionBriefPackPanelPreview() {
  final workspace = buildProjectDecisionsWorkspaceSummary(
    project: demoProjectPortfolio.first,
    dependencyTasks: const [],
    today: DateTime(2026, 6, 11),
  );

  return MaterialApp(
    home: Scaffold(
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: ProjectDecisionBriefPackPanel(
          summary: workspace.decisionBriefPackSummary,
        ),
      ),
    ),
  );
}
