// This file is generated by icon_font_generator.dart
// Don't edit this file manually.

import 'package:flutter/widgets.dart';


class CustomIcons {
  CustomIcons._();

  static const String _fontFamily = 'CustomIcons';

  /// chat icon
  static const IconData chat = IconData(
    0xE000,
    fontFamily: _fontFamily,
  );

  /// All available icons as a map
  static const Map<String, IconData> all = <String, IconData>{
    'chat': chat,
  };
}
