// enhanced_icon_font_generator.dart
import 'dart:io';
import 'dart:convert';
import 'package:path/path.dart' as path;

class EnhancedIconFontGenerator {
  final String inputDir;
  final String outputDir;
  final String fontName;
  final String className;
  final String fontFileName;

  EnhancedIconFontGenerator({
    required this.inputDir,
    required this.outputDir,
    required this.fontName,
    required this.className,
    required this.fontFileName,
  });

  Future<void> generate() async {
    await Directory(outputDir).create(recursive: true);

    final svgFiles = await _getSvgFiles();

    if (svgFiles.isEmpty) {
      throw Exception('No SVG files found in $inputDir');
    }

    // Generate configuration for external font tools
    await _generateIcoMoonConfig(svgFiles);
    await _generateFlutterIconFontConfig(svgFiles);
    await _generateDartClass(svgFiles);

    print('''
Icon Font Generation Complete!

Next steps:
1. Use the generated config with a font generation tool:
   - Option 1 (IcoMoon): Upload icomoon-config.json to https://icomoon.io/
   - Option 2 (Flutter Icon Font): Run: npx flutter-iconfont

2. Place the generated .ttf file in your Flutter project's fonts directory
3. Add the font to your pubspec.yaml:
   
   flutter:
     fonts:
       - family: $fontName
         fonts:
           - asset: fonts/${fontFileName}.ttf

4. Import and use the generated Dart class!
''');
  }

  Future<void> _generateIcoMoonConfig(List<Map<String, String>> icons) async {
    final config = {
      'IcoMoonType': 'selection',
      'icons':
          icons
              .map(
                (icon) => {
                  'icon': {
                    'paths': ['M0 0H1024V1024H0V0Z'], // Placeholder path
                    'tags': [icon['name']],
                  },
                  'attrs': [],
                  'properties': {
                    'order': icons.indexOf(icon) + 1,
                    'id': icons.indexOf(icon) + 1,
                    'name': icon['fileName'],
                    'prevSize': 32,
                    'code': int.parse(icon['codePoint']!),
                  },
                },
              )
              .toList(),
    };

    final configFile = File(path.join(outputDir, 'icomoon-config.json'));
    await configFile.writeAsString(jsonEncode(config));
  }

  Future<void> _generateFlutterIconFontConfig(
    List<Map<String, String>> icons,
  ) async {
    final config = {
      'font_family': fontName,
      'font_package': null,
      'icons':
          icons
              .map(
                (icon) => {
                  'name': icon['fileName'],
                  'style': 'regular',
                  'code': int.parse(icon['codePoint']!),
                },
              )
              .toList(),
    };

    final configFile = File(
      path.join(outputDir, 'flutter-iconfont-config.json'),
    );
    await configFile.writeAsString(jsonEncode(config));
  }

  Future<List<Map<String, String>>> _getSvgFiles() async {
    final dir = Directory(inputDir);
    final files = await dir.list().toList();

    final svgFiles = <Map<String, String>>[];
    int codePoint = 0xE000;

    for (final file in files) {
      if (file is File && file.path.toLowerCase().endsWith('.svg')) {
        final fileName = path.basenameWithoutExtension(file.path);
        final iconName = _toCamelCase(fileName);

        svgFiles.add({
          'name': iconName,
          'fileName': fileName,
          'filePath': file.path,
          'codePoint': '0x${codePoint.toRadixString(16).toUpperCase()}',
        });

        codePoint++;
      }
    }

    return svgFiles;
  }

  String _toCamelCase(String input) {
    final parts = input.replaceAll('-', '_').split('_');
    return parts.first.toLowerCase() +
        parts
            .skip(1)
            .map(
              (part) =>
                  part.isEmpty
                      ? ''
                      : part[0].toUpperCase() + part.substring(1).toLowerCase(),
            )
            .join();
  }

  Future<void> _generateDartClass(List<Map<String, String>> icons) async {
    final buffer = StringBuffer();

    buffer.writeln('''
// GENERATED CODE - DO NOT EDIT MANUALLY
// This file is generated by the Icon Font Generator

import 'package:flutter/widgets.dart';

/// $fontName icon font
class $className {
  $className._();
''');

    // Font family
    buffer.writeln("  static const String _kFontFamily = '$fontName';");
    buffer.writeln("  static const String _kFontPkg = null;\n");

    // Icons
    for (final icon in icons) {
      final name = icon['name']!;
      final codePoint = icon['codePoint']!;

      buffer.writeln('''
  /// ${icon['fileName']} icon
  static const IconData $name = IconData(
    $codePoint, 
    fontFamily: _kFontFamily,
    fontPackage: _kFontPkg,
  );''');
    }

    // All icons map
    buffer.writeln('\n  /// Map of all icon names to IconData');
    buffer.writeln('  static const Map<String, IconData> allIcons = {');
    for (final icon in icons) {
      buffer.writeln("    '${icon['name']}': ${icon['name']},");
    }
    buffer.writeln('  };');

    buffer.writeln('}');

    final dartFile = File(
      path.join(outputDir, '${className.toLowerCase()}.dart'),
    );
    await dartFile.writeAsString(buffer.toString());
  }
}
