import 'models/customer.dart';
import 'models/invoice.dart';
import 'models/payment.dart';
import 'models/vendor.dart';

final invoiceDummy = [
  Invoice(
    id: '1',
    vendorId: '1',
    invoiceNumber: 'INV-2025-001',
    invoiceDate: DateTime.now().subtract(const Duration(days: 20)),
    dueDate: DateTime.now().add(const Duration(days: 10)),
    amount: 2500.00,
    description: 'Office supplies',
    status: InvoiceStatus.pending,
  ),
  Invoice(
    id: '2',
    vendorId: '2',
    invoiceNumber: 'INV-2025-002',
    invoiceDate: DateTime.now().subtract(const Duration(days: 45)),
    dueDate: DateTime.now().subtract(const Duration(days: 15)),
    amount: 4750.00,
    description: 'Consulting services',
    status: InvoiceStatus.overdue,
  ),
  Invoice(
    id: '3',
    vendorId: '3',
    invoiceNumber: 'INV-2025-003',
    invoiceDate: DateTime.now().subtract(const Duration(days: 10)),
    dueDate: DateTime.now().add(const Duration(days: 20)),
    amount: 1850.00,
    description: 'Office furniture',
    status: InvoiceStatus.partiallyPaid,
  ),
  Invoice(
    id: '4',
    vendorId: '4',
    invoiceNumber: 'INV-2025-004',
    invoiceDate: DateTime.now().subtract(const Duration(days: 60)),
    dueDate: DateTime.now().subtract(const Duration(days: 30)),
    amount: 3200.00,
    description: 'Software licenses',
    status: InvoiceStatus.paid,
  ),
  Invoice(
    id: '5',
    vendorId: '5',
    invoiceNumber: 'INV-2025-005',
    invoiceDate: DateTime.now().subtract(const Duration(days: 15)),
    dueDate: DateTime.now().add(const Duration(days: 15)),
    amount: 5750.00,
    description: 'Shipping services',
    status: InvoiceStatus.disputed,
  ),
  Invoice(
    id: '1',
    customerId: '1',
    issueDate: DateTime.now().subtract(const Duration(days: 30)),
    dueDate: DateTime.now().subtract(const Duration(days: 15)),
    amount: 2500.00,
    reference: 'INV-2025-001',
    status: InvoiceStatus.overdue,
  ),
  Invoice(
    id: '2',
    customerId: '2',
    issueDate: DateTime.now().subtract(const Duration(days: 15)),
    dueDate: DateTime.now().add(const Duration(days: 15)),
    amount: 1800.00,
    reference: 'INV-2025-002',
    status: InvoiceStatus.partiallyPaid,
  ),
  Invoice(
    id: '3',
    customerId: '3',
    issueDate: DateTime.now().subtract(const Duration(days: 5)),
    dueDate: DateTime.now().add(const Duration(days: 25)),
    amount: 3200.00,
    reference: 'INV-2025-003',
    status: InvoiceStatus.outstanding,
  ),
  Invoice(
    id: '4',
    customerId: '1',
    issueDate: DateTime.now().subtract(const Duration(days: 60)),
    dueDate: DateTime.now().subtract(const Duration(days: 30)),
    amount: 1200.00,
    reference: 'INV-2025-004',
    status: InvoiceStatus.paid,
  ),
  Invoice(
    id: 'INV-001',
    customerId: '1',
    amount: 5000.00,
    issueDate: DateTime.now().subtract(Duration(days: 30)),
    dueDate: DateTime.now().subtract(Duration(days: 15)),
    payments: [
      Payment(
        id: 'PAY-001',
        invoiceId: 'INV-001',
        amount: 2500.00,
        paymentDate: DateTime.now().subtract(Duration(days: 20)),
        method: 'bank_transfer',
      ),
    ],
    status: InvoiceStatus.partiallyPaid,
  ),
  Invoice(
    id: 'INV-002',
    customerId: '2',
    amount: 7500.00,
    issueDate: DateTime.now().subtract(Duration(days: 20)),
    dueDate: DateTime.now().add(Duration(days: 10)),
    payments: [],
    status: InvoiceStatus.pending,
  ),
  Invoice(
    id: 'INV-003',
    customerId: '3',
    amount: 12000.00,
    issueDate: DateTime.now().subtract(Duration(days: 45)),
    dueDate: DateTime.now().subtract(Duration(days: 15)),
    payments: [
      Payment(
        id: 'PAY-002',
        invoiceId: 'INV-003',
        amount: 12000.00,
        paymentDate: DateTime.now().subtract(Duration(days: 10)),
        method: 'credit_card',
      ),
    ],
    status: InvoiceStatus.paid,
  ),
  Invoice(
    id: 'INV-004',
    customerId: '1',
    amount: 3000.00,
    issueDate: DateTime.now().subtract(Duration(days: 60)),
    dueDate: DateTime.now().subtract(Duration(days: 30)),
    payments: [],
    status: InvoiceStatus.overdue,
  ),
  Invoice(
    id: 'INV-005',
    customerId: '4',
    amount: 8500.00,
    issueDate: DateTime.now().subtract(Duration(days: 15)),
    dueDate: DateTime.now().add(Duration(days: 15)),
    payments: [
      Payment(
        id: 'PAY-003',
        invoiceId: 'INV-005',
        amount: 4250.00,
        paymentDate: DateTime.now().subtract(Duration(days: 5)),
        method: 'bank_transfer',
      ),
    ],
    status: InvoiceStatus.partiallyPaid,
  ),
];

final customerDummy = [
  Customer(
    id: '1',
    name: 'Acme Corp',
    email: 'accounts@acme.com',
    phone: '555-123-4567',
  ),
  Customer(
    id: '2',
    name: 'Wayne Enterprises',
    email: 'finance@wayne.com',
    phone: '555-987-6543',
  ),
  Customer(
    id: '3',
    name: 'Stark Industries',
    email: 'ar@stark.com',
    phone: '555-789-0123',
  ),
  Customer(
    id: '4',
    name: 'Umbrella Corp',
    email: 'billing@umbrella.com',
    phone: '555-456-7890',
  ),
  Customer(
    id: '1',
    name: 'Acme Corp',
    email: 'billing@acme.com',
    phone: '123-456-7890',
  ),
  Customer(
    id: '2',
    name: 'TechStart Inc',
    email: 'accounts@techstart.com',
    phone: '987-654-3210',
  ),
  Customer(
    id: '3',
    name: 'Global Services Ltd',
    email: 'finance@globalservices.com',
    phone: '555-555-5555',
  ),
];

final vendorDummy = [
  Vendor(
    id: '1',
    name: 'ABC Supplies',
    email: 'accounts@abcsupplies.com',
    phone: '+1-555-123-4567',
  ),
  Vendor(
    id: '2',
    name: 'XYZ Services',
    email: 'billing@xyzservices.com',
    phone: '+1-555-987-6543',
  ),
  Vendor(
    id: '3',
    name: 'Metro Office Furniture',
    email: 'ar@metrofurniture.com',
    phone: '+1-555-456-7890',
  ),
  Vendor(
    id: '4',
    name: 'Tech Innovations Ltd',
    email: 'payments@techinnovations.com',
    phone: '+1-555-222-3333',
  ),
  Vendor(
    id: '5',
    name: 'Global Logistics Inc',
    email: 'invoices@globallogistics.com',
    phone: '+1-555-789-0123',
  ),
  Vendor(
    id: 'V001',
    name: 'Tech Solutions Inc.',
    email: 'accounts@techsolutions.com',
    totalOutstanding: 4300.00,
  ),
  Vendor(
    id: 'V002',
    name: 'Office Supplies Co.',
    email: 'billing@officesupplies.com',
    totalOutstanding: 750.50,
  ),
  Vendor(
    id: 'V003',
    name: 'Marketing Agency',
    email: 'finance@marketingagency.com',
    totalOutstanding: 4200.00,
  ),
  Vendor(
    id: 'V004',
    name: 'Cloud Services Ltd.',
    email: 'payments@cloudservices.com',
    totalOutstanding: 1200.00,
  ),
];

final paymentDummy = [
  Payment(
    id: '1',
    invoiceId: '2',
    paymentDate: DateTime.now().subtract(const Duration(days: 5)),
    amount: 1000.00,
    reference: 'PAY-2025-001',
  ),
  Payment(
    id: '2',
    invoiceId: '4',
    paymentDate: DateTime.now().subtract(const Duration(days: 35)),
    amount: 1200.00,
    reference: 'PAY-2025-002',
  ),
];
