import '../states/pos_layout_provider.dart';
import 'pos_commerce_channel.dart';
import 'pos_commerce_channel_registry.dart';

final defaultPOSCommerceChannelRegistry = POSCommerceChannelRegistry(
  defaultChannelId: 'in_store',
  channels: const [
    POSCommerceChannel(
      id: 'in_store',
      kind: POSCommerceChannelKind.inStore,
      label: 'In-store',
      description: 'Cashier-led counter sales inside a physical location.',
      preferredLayout: POSLayoutPreference.auto,
      fulfillmentModes: [POSFulfillmentMode.immediateHandoff],
      capabilities: [
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.promotions,
        POSCommerceChannelCapability.offlineSelling,
        POSCommerceChannelCapability.returns,
      ],
      traits: ['counter', 'terminal-bound', 'walk-in'],
    ),
    POSCommerceChannel(
      id: 'kiosk',
      kind: POSCommerceChannelKind.kiosk,
      label: 'Kiosk',
      description: 'Self-service ordering on constrained public screens.',
      preferredLayout: POSLayoutPreference.compact,
      fulfillmentModes: [
        POSFulfillmentMode.pickup,
        POSFulfillmentMode.immediateHandoff,
      ],
      capabilities: [
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.fulfillmentTracking,
      ],
      traits: ['self-service', 'touch-first', 'guided'],
    ),
    POSCommerceChannel(
      id: 'mobile_pos',
      kind: POSCommerceChannelKind.mobilePOS,
      label: 'Mobile POS',
      description: 'Staff-assisted sales from phones or handheld devices.',
      preferredLayout: POSLayoutPreference.compact,
      fulfillmentModes: [
        POSFulfillmentMode.immediateHandoff,
        POSFulfillmentMode.pickup,
      ],
      capabilities: [
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.inventoryReservation,
        POSCommerceChannelCapability.offlineSelling,
      ],
      traits: ['portable', 'staff-assisted', 'line-busting'],
    ),
    POSCommerceChannel(
      id: 'web_store',
      kind: POSCommerceChannelKind.webStore,
      label: 'Web store',
      description: 'Owned online storefront for direct-to-customer orders.',
      preferredLayout: POSLayoutPreference.checkout,
      fulfillmentModes: [
        POSFulfillmentMode.pickup,
        POSFulfillmentMode.delivery,
        POSFulfillmentMode.shipment,
      ],
      capabilities: [
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.promotions,
        POSCommerceChannelCapability.inventoryReservation,
        POSCommerceChannelCapability.fulfillmentTracking,
      ],
      traits: ['owned-online', 'async-order', 'customer-account'],
    ),
    POSCommerceChannel(
      id: 'marketplace',
      kind: POSCommerceChannelKind.marketplace,
      label: 'Marketplace',
      description: 'Third-party marketplace orders with platform policies.',
      preferredLayout: POSLayoutPreference.checkout,
      fulfillmentModes: [
        POSFulfillmentMode.delivery,
        POSFulfillmentMode.shipment,
      ],
      capabilities: [
        POSCommerceChannelCapability.inventoryReservation,
        POSCommerceChannelCapability.fulfillmentTracking,
        POSCommerceChannelCapability.priceLists,
      ],
      traits: ['third-party', 'fees', 'policy-bound'],
    ),
    POSCommerceChannel(
      id: 'social_order',
      kind: POSCommerceChannelKind.socialOrder,
      label: 'Social order',
      description: 'Orders captured from chat, social, or assisted selling.',
      preferredLayout: POSLayoutPreference.checkout,
      fulfillmentModes: [
        POSFulfillmentMode.pickup,
        POSFulfillmentMode.delivery,
        POSFulfillmentMode.preorder,
      ],
      capabilities: [
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.fulfillmentTracking,
      ],
      traits: ['conversation-led', 'assisted', 'manual-confirmation'],
    ),
    POSCommerceChannel(
      id: 'delivery_app',
      kind: POSCommerceChannelKind.deliveryApp,
      label: 'Delivery app',
      description: 'Aggregator delivery orders with courier fulfillment.',
      preferredLayout: POSLayoutPreference.checkout,
      fulfillmentModes: [POSFulfillmentMode.delivery],
      capabilities: [
        POSCommerceChannelCapability.inventoryReservation,
        POSCommerceChannelCapability.fulfillmentTracking,
        POSCommerceChannelCapability.priceLists,
      ],
      traits: ['aggregator', 'courier', 'prep-time'],
    ),
    POSCommerceChannel(
      id: 'wholesale',
      kind: POSCommerceChannelKind.wholesale,
      label: 'Wholesale',
      description: 'B2B sales with negotiated pricing and staged fulfillment.',
      preferredLayout: POSLayoutPreference.counter,
      fulfillmentModes: [
        POSFulfillmentMode.pickup,
        POSFulfillmentMode.delivery,
        POSFulfillmentMode.shipment,
        POSFulfillmentMode.preorder,
      ],
      capabilities: [
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.priceLists,
        POSCommerceChannelCapability.inventoryReservation,
        POSCommerceChannelCapability.fulfillmentTracking,
        POSCommerceChannelCapability.returns,
      ],
      traits: ['b2b', 'price-list', 'account-managed'],
    ),
    POSCommerceChannel(
      id: 'field_sales',
      kind: POSCommerceChannelKind.fieldSales,
      label: 'Field sales',
      description: 'Staff selling outside the store with mobile fulfillment.',
      preferredLayout: POSLayoutPreference.compact,
      fulfillmentModes: [
        POSFulfillmentMode.fieldDelivery,
        POSFulfillmentMode.preorder,
      ],
      capabilities: [
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.inventoryReservation,
        POSCommerceChannelCapability.offlineSelling,
        POSCommerceChannelCapability.orderScheduling,
      ],
      traits: ['route-based', 'mobile-stock', 'scheduled'],
    ),
    POSCommerceChannel(
      id: 'phone_order',
      kind: POSCommerceChannelKind.phoneOrder,
      label: 'Phone order',
      description: 'Assisted remote orders captured by staff.',
      preferredLayout: POSLayoutPreference.checkout,
      fulfillmentModes: [
        POSFulfillmentMode.pickup,
        POSFulfillmentMode.delivery,
        POSFulfillmentMode.preorder,
      ],
      capabilities: [
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.promotions,
        POSCommerceChannelCapability.fulfillmentTracking,
        POSCommerceChannelCapability.orderScheduling,
      ],
      traits: ['assisted-remote', 'manual-confirmation', 'callback-ready'],
    ),
    POSCommerceChannel(
      id: 'table_service',
      kind: POSCommerceChannelKind.tableService,
      label: 'Table service',
      description: 'Dine-in ordering with table state and staged service.',
      preferredLayout: POSLayoutPreference.counter,
      fulfillmentModes: [POSFulfillmentMode.tableService],
      capabilities: [
        POSCommerceChannelCapability.payments,
        POSCommerceChannelCapability.customerIdentity,
        POSCommerceChannelCapability.promotions,
        POSCommerceChannelCapability.tableManagement,
        POSCommerceChannelCapability.fulfillmentTracking,
      ],
      traits: ['dine-in', 'seat-aware', 'course-staging'],
    ),
  ],
);
